### ISSUE TITLE
手动绑定是空白的

### ISSUE THREAD

**Issue by wang0251** [MoeNetwork/Tieba-Cloud-Sign#111]
新版本点击手动绑定，没地方输入BDUSS

**Comment by wang0251** [comment]
扫码绑定下面提示“Fatal error: Default value for parameters with a class type hint can only be NULL in /www/wwwroot/tieba/lib/class.misc.php on line 526”
手动绑定空白无法输入BDUSS

**Comment by BANKA2017** [comment]
https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/024ebaf8b58417cddbb7a6b89cb52771d0f7fa02/lib/class.misc.php#L526

此行提及的函数 `getTieba2()` 是用来获取关注的贴吧列表的，与登录没有任何关系，请检查文件完整性

**Comment by wang0251** [comment]
> https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/024ebaf8b58417cddbb7a6b89cb52771d0f7fa02/lib/class.misc.php#L526
> 
> 建议升级PHP到版本`7.1`以上;或删除掉变量前的`string`，`int`，`bool`，`: string`等，如果还显示在其他文件有相同错误继续就继续在那个文件删

感谢，升级了php7.4，已经正常了
