### ISSUE TITLE
刷新贴吧列表功能失效

### ISSUE THREAD

**Issue by sxx1314** [MoeNetwork/Tieba-Cloud-Sign#113]
最新master
刷新贴吧功能失效
自动刷新贴吧的插件也失效 https://github.com/chajianku/pch18_relist
有大佬来改改吗？

**Comment by sxx1314** [comment]
手贱清空之后瞬间傻眼。

**Comment by BANKA2017** [comment]
先确认php版本是不是低于 `7.1` ，如果低于 `7.1` 请升级或将

https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/024ebaf8b58417cddbb7a6b89cb52771d0f7fa02/lib/class.misc.php#L526

改成

```php
 public static function getTieba2($bduss, $pn = 1) { 
```

否则请在安装目录新建一个 `test.php` 的文件，写入

```php
<?php

$bduss = "";//这里填入bduss

ini_set('display_errors',1);
define('SYSTEM_DO_NOT_LOGIN', true);
require dirname(__FILE__).'/init.php';
global $m,$today,$i;
echo getTieba2($bduss);
```

然后执行看看有什么报错，敏感信息可以打码

**Comment by sxx1314** [comment]
> 先确认php版本是不是低于 `7.1` ，如果低于 `7.1` 请升级或将
> 
> https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/024ebaf8b58417cddbb7a6b89cb52771d0f7fa02/lib/class.misc.php#L526
> 
> 改成
> 
> ```
>  public static function getTieba2($bduss, $pn = 1) { 
> ```
> 
> 否则请在安装目录新建一个 `test.php` 的文件，写入
> 
> ```
> <?php
> 
> $bduss = "";//这里填入bduss
> 
> ini_set('display_errors',1);
> define('SYSTEM_DO_NOT_LOGIN', true);
> require dirname(__FILE__).'/init.php';
> global $m,$today,$i;
> echo getTieba2($bduss);
> ```
> 
> 然后执行看看有什么报错，敏感信息可以打码

感谢回复，待会尝试。
确实依旧停在php5.6， 因为是虚拟空间不是vps还有其他程序不能轻易升级。
另外问一下php5.6运行do.php 直接报500错误是什么问题，原来好好的，恢复了一下数据库就出这问题了，并且回退到3月底版本就正常。

**Comment by BANKA2017** [comment]
> > 先确认php版本是不是低于 `7.1` ，如果低于 `7.1` 请升级或将
> > https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/024ebaf8b58417cddbb7a6b89cb52771d0f7fa02/lib/class.misc.php#L526
> > 
> > 改成
> > ```
> >  public static function getTieba2($bduss, $pn = 1) { 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 否则请在安装目录新建一个 `test.php` 的文件，写入
> > ```
> > <?php
> > 
> > $bduss = "";//这里填入bduss
> > 
> > ini_set('display_errors',1);
> > define('SYSTEM_DO_NOT_LOGIN', true);
> > require dirname(__FILE__).'/init.php';
> > global $m,$today,$i;
> > echo getTieba2($bduss);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后执行看看有什么报错，敏感信息可以打码
> 
> 感谢回复.
> 确实依旧停在php5.6， 因为是虚拟空间不是vps还有其他程序不能轻易升级。
> 还有一个问题，修改之后php5.6运行do.php 依旧报500错误是什么问题，原来好好的，恢复了一下数据库就出这问题了，并且回退到3月底版本就正常。

这是因为最近我推的几个pr没考虑到[标量类型声明](https://www.php.net/manual/zh/migration70.new-features.php#migration70.new-features.scalar-type-declarations)是php7以后的特性，导致目前云签实际最低支持的php版本是php7，我会再推一个pr修复这个问题
