### ISSUE TITLE
所有链接都报CSRF防御错误

### ISSUE THREAD

**Issue by chenqs000** [MoeNetwork/Tieba-Cloud-Sign#115]
之前一切正常的，今天把程序删了重新用docker部署，结果不管是设置那里的提交更改还是退出登录，所有的链接都提示【CSRF防御：错误的请求来源】，而且更新那里一直提示【检查更新失败：无法获取最新版本信息。】

![微信截图_20210721165246](https://user-images.githubusercontent.com/34451009/126460819-4a679cd7-6cd5-4f96-a21b-4bb4ea818ff6.png)

**Comment by BANKA2017** [comment]
先将 https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/024ebaf8b58417cddbb7a6b89cb52771d0f7fa02/config.php#L22 改成 `false` 关掉csrf
然后打开 /index.php?plugin=wmzz_debug 找到 `$_SERVER['HTTP_REFERER']` 的域名填到 `设置中心 -> 全局设置 -> 站点地址` 里面，比如 `https://example.com/index.php?mod=admin:plugins` 就填 `https://example.com/` 然后提交保存
最后回去把 `config.php` 那里的 csrf 改回 `true`

**Comment by chenqs000** [comment]
> 先将
> 
> https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/024ebaf8b58417cddbb7a6b89cb52771d0f7fa02/config.php#L22
> 
> 改成 `false` 关掉csrf
> 然后打开 /index.php?plugin=wmzz_debug 找到 `$_SERVER['HTTP_REFERER']` 的域名填到 `设置中心 -> 全局设置 -> 站点地址` 里面，比如 `https://example.com/index.php?mod=admin:plugins` 就填 `https://example.com/` 然后提交保存
> 最后回去把 `config.php` 那里的 csrf 改回 `true`

不行， `设置中心 -> 全局设置 -> 站点地址` 的值就是 `$_SERVER['HTTP_REFERER']` 这个的地址，不过我的是IP地址。

**Comment by chenqs000** [comment]
> 先将
> 
> https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/024ebaf8b58417cddbb7a6b89cb52771d0f7fa02/config.php#L22
> 
> 改成 `false` 关掉csrf
> 然后打开 /index.php?plugin=wmzz_debug 找到 `$_SERVER['HTTP_REFERER']` 的域名填到 `设置中心 -> 全局设置 -> 站点地址` 里面，比如 `https://example.com/index.php?mod=admin:plugins` 就填 `https://example.com/` 然后提交保存
> 最后回去把 `config.php` 那里的 csrf 改回 `true`

顺便再问个问题，我更新那里刷多了几次检测到更新包了，但是更新时提示无法解压更新包，这个怎么解决？

**Comment by BANKA2017** [comment]
> > 先将
> > https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/024ebaf8b58417cddbb7a6b89cb52771d0f7fa02/config.php#L22
> > 
> > 改成 `false` 关掉csrf
> > 然后打开 /index.php?plugin=wmzz_debug 找到 `$_SERVER['HTTP_REFERER']` 的域名填到 `设置中心 -> 全局设置 -> 站点地址` 里面，比如 `https://example.com/index.php?mod=admin:plugins` 就填 `https://example.com/` 然后提交保存
> > 最后回去把 `config.php` 那里的 csrf 改回 `true`
> 
> 顺便再问个问题，我更新那里刷多了几次检测到更新包了，但是更新时提示无法解压更新包，这个怎么解决？

可能是权限不足？我发现docker安装的版本是4.92，现在版本应该是4.95

**Comment by BANKA2017** [comment]
* 执行 `docker ps -a` 找到一个名叫 `zsnmwy/tieba-cloud-sign` 的 container，记住那串 `CONTAINER ID`
* 执行 `docker exec  -it [CONTAINER ID]` (`[CONTAINER ID]` 就是上面记住的那个)，然后执行 `git pull`
* 执行 `exec` 退出

**Comment by chenqs000** [comment]
> * 执行 `docker ps -a` 找到一个名叫 `zsnmwy/tieba-cloud-sign` 的 container，记住那串 `CONTAINER ID`
> * 执行 `docker exec  -it [CONTAINER ID]` (`[CONTAINER ID]` 就是上面记住的那个)，然后执行 `git pull`
> * 执行 `exec` 退出

原来还可以这样，我之前还想着怎么把压缩包弄进去解压覆盖。
更新之后CSRF防御的问题也解决了。
非常感谢！

**Comment by xuwuqiang** [comment]
我的config.php代码在pull之后加入了很多^M符号，不知道是不是我编辑过的原因，然后我在https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/master/config.php上找到了原来的配置文件。
随后在绑定过程中发现在tc_baiduid表中新增加了portrait字段，修改表alter table tc_baiduid add portrait text not null after name; 
随后绑定成功。

**Comment by n0099** [comment]
> 我的config.php代码在pull之后加入了很多^M符号，不知道是不是我编辑过的原因
vim显示的^M就是\r换行符，我记得config.php里是\n而不是windows记事本用的\r\n换行符
