### ISSUE TITLE
插件提交

### ISSUE THREAD

**Issue by quericy** [MoeNetwork/Tieba-Cloud-Sign#12]
## 自定义每日签到邮件通知
ID：quericy_sign_mail
作者：[quericy](https://github.com/quericy/)
[https://github.com/quericy/quericy_sign_mail](https://github.com/quericy/quericy_sign_mail)

每日用户签到邮件通知，使用独立的SMTP服务器配置，支持tls、ssl加密，可自定义邮件标题和内容模板，优化报告页面执行效率和界面，基于D丶L的版本重写

**Comment by kenvix** [comment]
已添加
