### ISSUE TITLE
执行do.php时报错,消息：#-1 - 服务器不支持cURL

### ISSUE THREAD

**Issue by Weltolk** [MoeNetwork/Tieba-Cloud-Sign#125]
服务器和php都是有curl且可以正常使用的
```
root@VM-0-7-debian:/var/www/nginx/Tieba-Cloud-Sign# php do.php 
百度贴吧云签到 Ver.4.95  - 控制台模式
==========================================================
百度贴吧云签到 V4.95 (PHP 8.0.8) 在工作时发生致命的异常 @ 2021-09-05 13:08:11
消息：#-1 - 服务器不支持cURL

文件 | 行 | 代码 | 
/var/www/nginx/Tieba-Cloud-Sign/lib/class.wcurl.php | 24 | [抛出异常] | 
/var/www/nginx/Tieba-Cloud-Sign/lib/class.misc.php | 263 | __construct | 
/var/www/nginx/Tieba-Cloud-Sign/lib/class.misc.php | 306 | DoSign_Client | 
/var/www/nginx/Tieba-Cloud-Sign/lib/class.misc.php | 384 | DoSign_All | 
/var/www/nginx/Tieba-Cloud-Sign/lib/cron_system_sign.php | 20 | DoSign | 
/var/www/nginx/Tieba-Cloud-Sign/lib/class.cron.php | 192 | cron_system_sign | 
/var/www/nginx/Tieba-Cloud-Sign/lib/class.cron.php | 237 | run | 
/var/www/nginx/Tieba-Cloud-Sign/do.php | 51 | runall |
```

os version:debian 10
Tieba-Cloud-Sign version:latest
mysql version:mysql Ver 8.0.26 for Linux on x86_64 (MySQL Community Server - GPL)
installation method:直接git clone整个项目,然后chmod -R 777整个文件夹,最后在浏览器正常访问安装,用的mysqli,本地可以正常使用mysql,在浏览器执行定时任务system_sign可以正常签到

**Comment by Weltolk** [comment]
> 检查`/etc/php/8.0/cli/php.ini`的extension段是否保持着默认的注释状态（类似`;extenstion=curl.so`）

没有注释,用的版本是7.3,请问要换成新版本吗?extension段的所有东西都要注释掉吗

**Comment by n0099** [comment]
https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/8d217f71ddfa6975b693b4b17b93da570797e670/lib/class.wcurl.php#L23-L25
bash执行`php -i | grep -C 5 curl`

**Comment by Weltolk** [comment]
> bash执行`php -i | grep -C 5 curl`

返回为空...
```
root@VM-0-7-debian:~# php -i | grep -C 5 curl
root@VM-0-7-debian:~# 
```

贴一下php.ini有关curl的配置
```
extension=curl

[curl]
;curl.cainfo =
```

**Comment by Weltolk** [comment]
> https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/8d217f71ddfa6975b693b4b17b93da570797e670/lib/class.wcurl.php#L23-L25
> 
> 
> bash执行`php -i | grep -C 5 curl`

已经在用docker的了,目前有一个问题,就是"检查更新"的时候不论是用github还是gitee,都是显示"检查更新失败：无法获取最新版本信息。",五天之前和今天都尝试了"检查更新",都是报这个错

**Comment by BANKA2017** [comment]
检查是不是只装了php7.3的 `php7.3-curl`，而没有安装 `php8.0-curl`

> 没有注释,用的版本是**7.3**,请问要换成新版本吗?extension段的所有东西都要注释掉吗


> ```
> 百度贴吧云签到 V4.95 (PHP 8.0.8) 在工作时发生致命的异常 @ 2021-09-05 13:08:11
> ```

----

自动检查更新早废了，失败才正常，手动覆盖解决问题

**Comment by Weltolk** [comment]
> 检查是不是只装了php7.3的 `php7.3-curl`，而没有安装 `php8.0-curl`
> 
> > 没有注释,用的版本是**7.3**,请问要换成新版本吗?extension段的所有东西都要注释掉吗
> 
> > ```
> > 百度贴吧云签到 V4.95 (PHP 8.0.8) 在工作时发生致命的异常 @ 2021-09-05 13:08:11
> > ```
> 
> 自动检查更新早废了，失败才正常，手动覆盖解决问题

8.0应该是没装

请问docker也是直接覆盖就可以吗

**Comment by n0099** [comment]
> > bash执行`php -i | grep -C 5 curl`
> 
> 返回为空...
> 
> ```
> root@VM-0-7-debian:~# php -i | grep -C 5 curl
> root@VM-0-7-debian:~# 
> ```
> 
> 贴一下php.ini有关curl的配置
> 
> ```
> extension=curl
> 
> [curl]
> ;curl.cainfo =
> ```

您是不是装了多个版本php（看看`whereis php`），这个php.ini是cli还是fpm的？

**Comment by Weltolk** [comment]
> > > bash执行`php -i | grep -C 5 curl`
> > 
> > 
> > 返回为空...
> > ```
> > root@VM-0-7-debian:~# php -i | grep -C 5 curl
> > root@VM-0-7-debian:~# 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 贴一下php.ini有关curl的配置
> > ```
> > extension=curl
> > 
> > [curl]
> > ;curl.cainfo =
> > ```
> 
> 您是不是装了多个版本php（看看`whereis php`），这个php.ini是cli还是fpm的？

```
root@VM-0-7-debian:~# cd /etc/php/
root@VM-0-7-debian:/etc/php# ls
7.3
root@VM-0-7-debian:/etc/php# ls 7.3/
cli  fpm  mods-available
root@VM-0-7-debian:/etc/php# whereis php
php: /usr/bin/php7.3 /usr/bin/php /usr/lib/php /etc/php /usr/local/bin/php /usr/local/lib/php /usr/local/php /usr/share/php7.3-common /usr/share/php7.3-opcache /usr/share/php7.3-curl /usr/share/php7.3-dba /usr/share/php7.3-json /usr/share/php7.3-readline /usr/share/php7.3-zip /usr/share/php7.3-xml /usr/share/php /usr/share/php7.3-mbstring /usr/share/php7.3-mysql /usr/share/php7.3-gd /usr/share/man/man1/php.1.gz
root@VM-0-7-debian:/etc/php# 
```

不好意思,php属实是不怎么了解...
另外问下docker的怎么更新...自动更新一直失败

**Comment by Weltolk** [comment]
> > > bash执行`php -i | grep -C 5 curl`
> > 
> > 
> > 返回为空...
> > ```
> > root@VM-0-7-debian:~# php -i | grep -C 5 curl
> > root@VM-0-7-debian:~# 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 贴一下php.ini有关curl的配置
> > ```
> > extension=curl
> > 
> > [curl]
> > ;curl.cainfo =
> > ```
> 
> 您是不是装了多个版本php（看看`whereis php`），这个php.ini是cli还是fpm的？

php.ini是cli的

**Comment by n0099** [comment]
> > > > bash执行`php -i | grep -C 5 curl`
> > > 
> > > 
> > > 返回为空...
> > > ```
> > > root@VM-0-7-debian:~# php -i | grep -C 5 curl
> > > root@VM-0-7-debian:~# 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 贴一下php.ini有关curl的配置
> > > ```
> > > extension=curl
> > > 
> > > [curl]
> > > ;curl.cainfo =
> > > ```
> > 
> > 
> > 您是不是装了多个版本php（看看`whereis php`），这个php.ini是cli还是fpm的？
> 
> ```
> root@VM-0-7-debian:~# cd /etc/php/
> root@VM-0-7-debian:/etc/php# ls
> 7.3
> root@VM-0-7-debian:/etc/php# ls 7.3/
> cli  fpm  mods-available
> root@VM-0-7-debian:/etc/php# whereis php
> php: /usr/bin/php7.3 /usr/bin/php /usr/lib/php /etc/php /usr/local/bin/php /usr/local/lib/php /usr/local/php /usr/share/php7.3-common /usr/share/php7.3-opcache /usr/share/php7.3-curl /usr/share/php7.3-dba /usr/share/php7.3-json /usr/share/php7.3-readline /usr/share/php7.3-zip /usr/share/php7.3-xml /usr/share/php /usr/share/php7.3-mbstring /usr/share/php7.3-mysql /usr/share/php7.3-gd /usr/share/man/man1/php.1.gz
> root@VM-0-7-debian:/etc/php# 
> ```
> 
> 不好意思,php属实是不怎么了解... 另外问下docker的怎么更新...自动更新一直失败

更新一般是git pull然后覆盖文件

**Comment by n0099** [comment]
> > > > bash执行`php -i | grep -C 5 curl`
> > > 
> > > 
> > > 返回为空...
> > > ```
> > > root@VM-0-7-debian:~# php -i | grep -C 5 curl
> > > root@VM-0-7-debian:~# 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 贴一下php.ini有关curl的配置
> > > ```
> > > extension=curl
> > > 
> > > [curl]
> > > ;curl.cainfo =
> > > ```
> > 
> > 
> > 您是不是装了多个版本php（看看`whereis php`），这个php.ini是cli还是fpm的？
> 
> php.ini是cli的

看看`/etc/php/7.3/mods-available`里有无curl.ini，如果没有试试`apt install php-curl`

**Comment by Weltolk** [comment]
> > > > > bash执行`php -i | grep -C 5 curl`
> > > > 
> > > > 
> > > > 返回为空...
> > > > ```
> > > > root@VM-0-7-debian:~# php -i | grep -C 5 curl
> > > > root@VM-0-7-debian:~# 
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 贴一下php.ini有关curl的配置
> > > > ```
> > > > extension=curl
> > > > 
> > > > [curl]
> > > > ;curl.cainfo =
> > > > ```
> > > 
> > > 
> > > 您是不是装了多个版本php（看看`whereis php`），这个php.ini是cli还是fpm的？
> > 
> > 
> > php.ini是cli的
> 
> 看看`/etc/php/7.3/mods-available`里有无curl.ini，如果没有试试`apt install php-curl`，如果找不到包请引入这个ppa https://launchpad.net/~ondrej/+archive/ubuntu/php

有这个文件,下面是文件内容
```
root@VM-0-7-debian:/etc/php/7.3/mods-available# ls -l | grep curl
-rw-r--r-- 1 root root 68 Feb 14  2021 curl.ini
root@VM-0-7-debian:/etc/php/7.3/mods-available# cat curl.ini 
; configuration for php curl module
; priority=20
extension=curl.so
root@VM-0-7-debian:/etc/php/7.3/mods-available# 

```

**Comment by Weltolk** [comment]
> > > > > bash执行`php -i | grep -C 5 curl`
> > > > 
> > > > 
> > > > 返回为空...
> > > > ```
> > > > root@VM-0-7-debian:~# php -i | grep -C 5 curl
> > > > root@VM-0-7-debian:~# 
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 贴一下php.ini有关curl的配置
> > > > ```
> > > > extension=curl
> > > > 
> > > > [curl]
> > > > ;curl.cainfo =
> > > > ```
> > > 
> > > 
> > > 您是不是装了多个版本php（看看`whereis php`），这个php.ini是cli还是fpm的？
> > 
> > 
> > ```
> > root@VM-0-7-debian:~# cd /etc/php/
> > root@VM-0-7-debian:/etc/php# ls
> > 7.3
> > root@VM-0-7-debian:/etc/php# ls 7.3/
> > cli  fpm  mods-available
> > root@VM-0-7-debian:/etc/php# whereis php
> > php: /usr/bin/php7.3 /usr/bin/php /usr/lib/php /etc/php /usr/local/bin/php /usr/local/lib/php /usr/local/php /usr/share/php7.3-common /usr/share/php7.3-opcache /usr/share/php7.3-curl /usr/share/php7.3-dba /usr/share/php7.3-json /usr/share/php7.3-readline /usr/share/php7.3-zip /usr/share/php7.3-xml /usr/share/php /usr/share/php7.3-mbstring /usr/share/php7.3-mysql /usr/share/php7.3-gd /usr/share/man/man1/php.1.gz
> > root@VM-0-7-debian:/etc/php# 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不好意思,php属实是不怎么了解... 另外问下docker的怎么更新...自动更新一直失败
> 
> 更新一般是git pull然后覆盖文件

请问配置和账号是存在config.php和数据库里吗?更新的时候保留这两个东西就可以吗?

**Comment by n0099** [comment]
> > > 不好意思,php属实是不怎么了解... 另外问下docker的怎么更新...自动更新一直失败
> > 
> > 
> > 更新一般是git pull然后覆盖文件
> 
> 请问配置和账号是存在config.php和数据库里吗?更新的时候保留这两个东西就可以吗?

是

**Comment by n0099** [comment]
> > > > > > bash执行`php -i | grep -C 5 curl`
> > > > > 
> > > > > 
> > > > > 返回为空...
> > > > > ```
> > > > > root@VM-0-7-debian:~# php -i | grep -C 5 curl
> > > > > root@VM-0-7-debian:~# 
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 贴一下php.ini有关curl的配置
> > > > > ```
> > > > > extension=curl
> > > > > 
> > > > > [curl]
> > > > > ;curl.cainfo =
> > > > > ```
> > > > 
> > > > 
> > > > 您是不是装了多个版本php（看看`whereis php`），这个php.ini是cli还是fpm的？
> > > 
> > > 
> > > php.ini是cli的
> > 
> > 
> > 看看`/etc/php/7.3/mods-available`里有无curl.ini，如果没有试试`apt install php-curl`，如果找不到包请引入这个ppa https://launchpad.net/~ondrej/+archive/ubuntu/php
> 
> 有这个文件,下面是文件内容
> 
> ```
> root@VM-0-7-debian:/etc/php/7.3/mods-available# ls -l | grep curl
> -rw-r--r-- 1 root root 68 Feb 14  2021 curl.ini
> root@VM-0-7-debian:/etc/php/7.3/mods-available# cat curl.ini 
> ; configuration for php curl module
> ; priority=20
> extension=curl.so
> root@VM-0-7-debian:/etc/php/7.3/mods-available# 
> ```

看看`php -i | grep ini` 和 `dpkg -l | grep curl`

**Comment by Weltolk** [comment]
> > > > 不好意思,php属实是不怎么了解... 另外问下docker的怎么更新...自动更新一直失败
> > > 
> > > 
> > > 更新一般是git pull然后覆盖文件
> > 
> > 
> > 请问配置和账号是存在config.php和数据库里吗?更新的时候保留这两个东西就可以吗?
> 
> 是

好的谢谢

**Comment by Weltolk** [comment]
> 

```
root@VM-0-7-debian:~# php -i | grep ini
Configuration File (php.ini) Path => /usr/local/lib
Scan this dir for additional .ini files => (none)
Additional .ini files parsed => (none)
user_ini.cache_ttl => 300 => 300
user_ini.filename => .user.ini => .user.ini
Classes => AppendIterator, ArrayIterator, ArrayObject, BadFunctionCallException, BadMethodCallException, CachingIterator, CallbackFilterIterator, DirectoryIterator, DomainException, EmptyIterator, FilesystemIterator, FilterIterator, GlobIterator, InfiniteIterator, InvalidArgumentException, IteratorIterator, LengthException, LimitIterator, LogicException, MultipleIterator, NoRewindIterator, OutOfBoundsException, OutOfRangeException, OverflowException, ParentIterator, RangeException, RecursiveArrayIterator, RecursiveCachingIterator, RecursiveCallbackFilterIterator, RecursiveDirectoryIterator, RecursiveFilterIterator, RecursiveIteratorIterator, RecursiveRegexIterator, RecursiveTreeIterator, RegexIterator, RuntimeException, SplDoublyLinkedList, SplFileInfo, SplFileObject, SplFixedArray, SplHeap, SplMinHeap, SplMaxHeap, SplObjectStorage, SplPriorityQueue, SplQueue, SplStack, SplTempFileObject, UnderflowException, UnexpectedValueException
root@VM-0-7-debian:~# dpkg -l | grep curl
ii  curl                            7.64.0-4+deb10u2             amd64        command line tool for transferring data with URL syntax
ii  libcurl3-gnutls:amd64           7.64.0-4+deb10u2             amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  libcurl4:amd64                  7.64.0-4+deb10u2             amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  php7.3-curl                     7.3.29-1~deb10u1             amd64        CURL module for PHP
ii  python3-pycurl                  7.43.0.2-0.1                 amd64        Python bindings to libcurl (Python 3)
root@VM-0-7-debian:~# 
```

**Comment by n0099** [comment]
> > 
> 
> ```
> root@VM-0-7-debian:~# php -i | grep ini
> Configuration File (php.ini) Path => /usr/local/lib
> Scan this dir for additional .ini files => (none)
> Additional .ini files parsed => (none)
> user_ini.cache_ttl => 300 => 300
> user_ini.filename => .user.ini => .user.ini
> Classes => AppendIterator, ArrayIterator, ArrayObject, BadFunctionCallException, BadMethodCallException, CachingIterator, CallbackFilterIterator, DirectoryIterator, DomainException, EmptyIterator, FilesystemIterator, FilterIterator, GlobIterator, InfiniteIterator, InvalidArgumentException, IteratorIterator, LengthException, LimitIterator, LogicException, MultipleIterator, NoRewindIterator, OutOfBoundsException, OutOfRangeException, OverflowException, ParentIterator, RangeException, RecursiveArrayIterator, RecursiveCachingIterator, RecursiveCallbackFilterIterator, RecursiveDirectoryIterator, RecursiveFilterIterator, RecursiveIteratorIterator, RecursiveRegexIterator, RecursiveTreeIterator, RegexIterator, RuntimeException, SplDoublyLinkedList, SplFileInfo, SplFileObject, SplFixedArray, SplHeap, SplMinHeap, SplMaxHeap, SplObjectStorage, SplPriorityQueue, SplQueue, SplStack, SplTempFileObject, UnderflowException, UnexpectedValueException
> root@VM-0-7-debian:~# dpkg -l | grep curl
> ii  curl                            7.64.0-4+deb10u2             amd64        command line tool for transferring data with URL syntax
> ii  libcurl3-gnutls:amd64           7.64.0-4+deb10u2             amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
> ii  libcurl4:amd64                  7.64.0-4+deb10u2             amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
> ii  php7.3-curl                     7.3.29-1~deb10u1             amd64        CURL module for PHP
> ii  python3-pycurl                  7.43.0.2-0.1                 amd64        Python bindings to libcurl (Python 3)
> root@VM-0-7-debian:~# 
> ```

看看`/usr/local/lib/php.ini`

**Comment by Weltolk** [comment]
> > > 
> > 
> > 
> > ```
> > root@VM-0-7-debian:~# php -i | grep ini
> > Configuration File (php.ini) Path => /usr/local/lib
> > Scan this dir for additional .ini files => (none)
> > Additional .ini files parsed => (none)
> > user_ini.cache_ttl => 300 => 300
> > user_ini.filename => .user.ini => .user.ini
> > Classes => AppendIterator, ArrayIterator, ArrayObject, BadFunctionCallException, BadMethodCallException, CachingIterator, CallbackFilterIterator, DirectoryIterator, DomainException, EmptyIterator, FilesystemIterator, FilterIterator, GlobIterator, InfiniteIterator, InvalidArgumentException, IteratorIterator, LengthException, LimitIterator, LogicException, MultipleIterator, NoRewindIterator, OutOfBoundsException, OutOfRangeException, OverflowException, ParentIterator, RangeException, RecursiveArrayIterator, RecursiveCachingIterator, RecursiveCallbackFilterIterator, RecursiveDirectoryIterator, RecursiveFilterIterator, RecursiveIteratorIterator, RecursiveRegexIterator, RecursiveTreeIterator, RegexIterator, RuntimeException, SplDoublyLinkedList, SplFileInfo, SplFileObject, SplFixedArray, SplHeap, SplMinHeap, SplMaxHeap, SplObjectStorage, SplPriorityQueue, SplQueue, SplStack, SplTempFileObject, UnderflowException, UnexpectedValueException
> > root@VM-0-7-debian:~# dpkg -l | grep curl
> > ii  curl                            7.64.0-4+deb10u2             amd64        command line tool for transferring data with URL syntax
> > ii  libcurl3-gnutls:amd64           7.64.0-4+deb10u2             amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
> > ii  libcurl4:amd64                  7.64.0-4+deb10u2             amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
> > ii  php7.3-curl                     7.3.29-1~deb10u1             amd64        CURL module for PHP
> > ii  python3-pycurl                  7.43.0.2-0.1                 amd64        Python bindings to libcurl (Python 3)
> > root@VM-0-7-debian:~# 
> > ```
> 
> 看看`/usr/local/lib/php.ini` 根据https://www.php.net/manual/en/configuration.file.php ，可能您的php编译选项`--with-config-file-scan-dir`不是`/etc/php`而是这个，您是从ppa那个包源（https://launchpad.net/~ondrej/+archive/ubuntu/php ）安装的php吗？

```
root@VM-0-7-debian:/usr/local/lib# ls -l | grep php.ini
root@VM-0-7-debian:/usr/local/lib# ls
libpython3.9.a	php  pkgconfig	python2.7  python3.7  python3.9
root@VM-0-7-debian:/usr/local/lib# cd php/
root@VM-0-7-debian:/usr/local/lib/php# ls
build  extensions
root@VM-0-7-debian:/usr/local/lib/php#
```
没有这个文件.......

我是从官网下的源码编译的,对php基本不懂,当时编译时添加的选项貌似是在网上找的,抱歉.....

**Comment by n0099** [comment]
> > > > 
> > > 
> > > 
> > > ```
> > > root@VM-0-7-debian:~# php -i | grep ini
> > > Configuration File (php.ini) Path => /usr/local/lib
> > > Scan this dir for additional .ini files => (none)
> > > Additional .ini files parsed => (none)
> > > user_ini.cache_ttl => 300 => 300
> > > user_ini.filename => .user.ini => .user.ini
> > > Classes => AppendIterator, ArrayIterator, ArrayObject, BadFunctionCallException, BadMethodCallException, CachingIterator, CallbackFilterIterator, DirectoryIterator, DomainException, EmptyIterator, FilesystemIterator, FilterIterator, GlobIterator, InfiniteIterator, InvalidArgumentException, IteratorIterator, LengthException, LimitIterator, LogicException, MultipleIterator, NoRewindIterator, OutOfBoundsException, OutOfRangeException, OverflowException, ParentIterator, RangeException, RecursiveArrayIterator, RecursiveCachingIterator, RecursiveCallbackFilterIterator, RecursiveDirectoryIterator, RecursiveFilterIterator, RecursiveIteratorIterator, RecursiveRegexIterator, RecursiveTreeIterator, RegexIterator, RuntimeException, SplDoublyLinkedList, SplFileInfo, SplFileObject, SplFixedArray, SplHeap, SplMinHeap, SplMaxHeap, SplObjectStorage, SplPriorityQueue, SplQueue, SplStack, SplTempFileObject, UnderflowException, UnexpectedValueException
> > > root@VM-0-7-debian:~# dpkg -l | grep curl
> > > ii  curl                            7.64.0-4+deb10u2             amd64        command line tool for transferring data with URL syntax
> > > ii  libcurl3-gnutls:amd64           7.64.0-4+deb10u2             amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
> > > ii  libcurl4:amd64                  7.64.0-4+deb10u2             amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
> > > ii  php7.3-curl                     7.3.29-1~deb10u1             amd64        CURL module for PHP
> > > ii  python3-pycurl                  7.43.0.2-0.1                 amd64        Python bindings to libcurl (Python 3)
> > > root@VM-0-7-debian:~# 
> > > ```
> > 
> > 
> > 看看`/usr/local/lib/php.ini` 根据https://www.php.net/manual/en/configuration.file.php ，可能您的php编译选项`--with-config-file-scan-dir`不是`/etc/php`而是这个，您是从ppa那个包源（https://launchpad.net/~ondrej/+archive/ubuntu/php ）安装的php吗？
> 
> ```
> root@VM-0-7-debian:/usr/local/lib# ls -l | grep php.ini
> root@VM-0-7-debian:/usr/local/lib# ls
> libpython3.9.a	php  pkgconfig	python2.7  python3.7  python3.9
> root@VM-0-7-debian:/usr/local/lib# cd php/
> root@VM-0-7-debian:/usr/local/lib/php# ls
> build  extensions
> root@VM-0-7-debian:/usr/local/lib/php#
> ```
> 
> 没有这个文件.......
> 
> 我是从官网下的源码编译的,对php基本不懂,当时编译时添加的选项貌似是在网上找的,抱歉.....

为什么不ppa包源安装

**Comment by Weltolk** [comment]
> ii  libcurl4:amd64                  7.64.0-4+deb10u2             amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)

php官网没写这个方法.......请问apt的话要安装哪个包

**Comment by n0099** [comment]
> > ii  libcurl4:amd64                  7.64.0-4+deb10u2             amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
> 
> php官网没写这个方法.......请问apt的话要安装哪个包

https://launchpad.net/~ondrej/+archive/ubuntu/php

**Comment by Weltolk** [comment]
> > > ii  libcurl4:amd64                  7.64.0-4+deb10u2             amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
> > 
> > 
> > php官网没写这个方法.......请问apt的话要安装哪个包
> 
> https://launchpad.net/~ondrej/+archive/ubuntu/php

好的,谢谢,请问如果想在物理机和docker之间转移,把config.php和整个database copy过去就可以了是嘛

**Comment by n0099** [comment]
> > > > ii  libcurl4:amd64                  7.64.0-4+deb10u2             amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
> > > 
> > > 
> > > php官网没写这个方法.......请问apt的话要安装哪个包
> > 
> > 
> > https://launchpad.net/~ondrej/+archive/ubuntu/php
> 
> 好的,谢谢,请问如果想在物理机和docker之间转移,把config.php和整个database copy过去就可以了是嘛

是

**Comment by Weltolk** [comment]
> > > > > ii  libcurl4:amd64                  7.64.0-4+deb10u2             amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
> > > > 
> > > > 
> > > > php官网没写这个方法.......请问apt的话要安装哪个包
> > > 
> > > 
> > > https://launchpad.net/~ondrej/+archive/ubuntu/php
> > 
> > 
> > 好的,谢谢,请问如果想在物理机和docker之间转移,把config.php和整个database copy过去就可以了是嘛
> 
> 是

好的,谢谢
