### ISSUE TITLE
手动绑定提示错误

### ISSUE THREAD

**Issue by small-bao** [MoeNetwork/Tieba-Cloud-Sign#129]
手动绑定提示错误：
您的 BDUSS Cookie 信息有误，请核验后重新绑定。

确定BDUSS无误，接口https://tieba.baidu.com/mg/o/profile?format=json可正常显示自己的信息。

试过多种获取BDUSS都无法手动绑定，提示错误，扫码绑定的QR码显示不出来。

**Comment by miemie2104** [comment]
遇到一样的问题 正在找解决方法

**Comment by BANKA2017** [comment]
首先，这是因为赋值 `=` 打成相等 `==` 导致 ajax 返回的对象中缺少 `msg` ，从而使前端填上了默认模板上的消息 

https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/6bc21131e7ca6814511c56a484737bb650fd316e/templates/baiduid.php#L93-L96

pr合并前的修改方法是将以下部分的所有 `$loginResult` 后面的 `==` 修改为 `=`，如 `$loginResult["error"] == -11;` 改为 `$loginResult["error"] = -11;`（共计 6 处）

https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/6bc21131e7ca6814511c56a484737bb650fd316e/ajax.php#L234-L250
