### ISSUE TITLE
小白不明白问题出在哪里。。求助大佬

### ISSUE THREAD

**Issue by YFFtYHwsdj** [MoeNetwork/Tieba-Cloud-Sign#133]
PHP Fatal error:  Uncaught Exception: MySQL 语句执行错误：<br/><b>语句：</b>SELECT * FROM tc_options<br/><b>错误：</b>#1146 - Table 'tiebacloud.tc_options' doesn'
t exist in /var/www/lib/class.mysqli.php:120                                                                                                            
Stack trace:                                                                                                                                            
#0 /var/www/lib/reg.php(21): wmysql->query()                                                                                                            
#1 /var/www/init.php(46): require('/var/www/lib/re...')                                                                                                 
#2 /var/www/do.php(3): require('/var/www/init.p...')                                                                                                    
#3 {main}                                                                                                                                               
  thrown in /var/www/lib/class.mysqli.php on line 120

**Comment by leonchanithotmail** [comment]
> PHP Fatal error: Uncaught Exception: MySQL 语句执行错误：语句：SELECT * FROM tc_options错误：#1146 - Table 'tiebacloud.tc_options' doesn' t exist in /var/www/lib/class.mysqli.php:120 Stack trace: #0 /var/www/lib/reg.php(21): wmysql->query() #1 /var/www/init.php(46): require('/var/www/lib/re...') #2 /var/www/do.php(3): require('/var/www/init.p...') #3 {main} thrown in /var/www/lib/class.mysqli.php on line 120
请教一下，这个问题的解决方法具体是怎么操作的，有点看不懂。

**Comment by n0099** [comment]
浏览器访问`http://您的域名/您的tc目录/setup/index.php`
然后在bash/sftp里删除`您的tc目录/setup`目录

**Comment by BANKA2017** [comment]
> 浏览器访问`http://您的域名/您的tc目录/setup/index.php` 然后在bash/sftp里删除`您的tc目录/setup`目录

不要误导，setup目录还是要留下的，但在安装完以后里面的文件只需要留下 install.lock，其他的文件都可以删除

**Comment by n0099** [comment]
为什么留一个空目录

**Comment by Orange-Summer** [comment]
我访问/setup/index.php就报这个错，另外想问一下tc目录是什么呀？
