### ISSUE TITLE
4.6 自动刷新贴吧列表 有问题

### ISSUE THREAD

**Issue by huqichun** [MoeNetwork/Tieba-Cloud-Sign#14]
管理员只能刷新自己的贴吧列表 ， 没法刷新用户的   ， 导入同一个数据库  ，4.4就没问题 ，  还有就是刷新列表过后域名跳转https://   ，导致不能显示刷新结果

好吧 ， 没看见  ，原来4.7已经解决了    ，不过希望能解决下域名跳转https:// 问题

http://baidu.xxxx.cn/index.php?mod=admin:setplug&plug=pch18_relist&ref=all
自动返回
https://baidu.xxxx.cn/index.php?mod=admin:setplug&plug=pch18_relist&isok=已刷新完所有用户贴吧列表

**Comment by kenvix** [comment]
域名跳转https:// 问题可能是你的站点地址设置不对 看看全局设置

**Comment by huqichun** [comment]
靠 还真是我设置错误  谢谢   打扰了
