### ISSUE TITLE
不签到，日志里写“10点时忽略签到”

### ISSUE THREAD

**Issue by xiang32** [MoeNetwork/Tieba-Cloud-Sign#140]
如题，cron也弄好了，签到设置里的“签到开始时间”设置为了10点，cron的计划任务也设置成了10点，是不是有什么冲突······
![tmp](https://user-images.githubusercontent.com/27066986/148673695-1d8ce5f3-7d89-46ae-a20f-623b9b55c869.jpg)

**Comment by BANKA2017** [comment]
根据设置界面的语句
>24小时制。例如设为-1，则从0点开始签到

和以下代码
https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/7078573eab02a48efcb66b1dad415a908dac9f65/lib/class.misc.php#L355-L357

你可能需要在 `签到开始时间` 填写 `9` 

---

ps: 截图所示的cron设置每天只会在十点整执行一次，建议设置为

```shell
* * * * * php /你的目录/do.php
```

**Comment by xiang32** [comment]
> 根据设置界面的语句
> 
> > 24小时制。例如设为-1，则从0点开始签到
> 
> 和以下代码
> 
> https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/7078573eab02a48efcb66b1dad415a908dac9f65/lib/class.misc.php#L355-L357
> 
> 你可能需要在 `签到开始时间` 填写 `9`
> 
> ps: 截图所示的cron设置每天只会在十点整执行一次，建议设置为
> 
> ```shell
> * * * * * php /你的目录/do.php
> ```

感谢大佬指点，问题已解决，是我对签到系统的理解出了问题

**Comment by Orange-Summer** [comment]
这个容易误解啊😂我以为意思是数值不在0-24范围内的话默认为0
