### ISSUE TITLE
用 docker compose 搭建的话，需要手动设置 cron 吗？

### ISSUE THREAD

**Issue by rolling2022** [MoeNetwork/Tieba-Cloud-Sign#142]
https://baiduqiandao.com/

我搭建了一个云签到的网站，已经搭建完成了。完成的页面告诉我，需要每分钟执行一个 cron，运行 `do.php`，我想问一下，docker里面比较难操作，我需要改写 `Dockerfile` 来达成这个 cron 的要求吗？

实际上我发现网站的 cron 定时任务已经在运行了。所以或许是提示有问题？

**Comment by YuChenRX** [comment]
要的

**Comment by VwEl** [comment]
所以需要加嘛？

**Comment by BANKA2017** [comment]
> 所以需要加嘛？

根据

https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/f8bc2b1dc122795c9568cfcf54517305a14d3be3/docker/s6-overlay/etc/cont-init.d/30-set-crontab#L1-L8 

docker部署不需要手动添加，是开箱即用的
