### ISSUE TITLE
疑似软件被篡改

### ISSUE THREAD

**Issue by ak-tequila** [MoeNetwork/Tieba-Cloud-Sign#146]
最新安装的版本左下角“问题反馈”的url被篡改指向了一个博彩网站，希望官方注意并修复一下，谢谢。

**Comment by BANKA2017** [comment]
软件没有被篡改，那个是以前论坛的链接，现在被菠菜网站买下来当跳转用了

**Comment by ak-tequila** [comment]
好的感谢答疑

**Comment by n0099** [comment]
菠菜网站会想到买stusgame.com估计也是看到互联网上对此域的外链比较多所以可能自带很多流量，因为所有公开的tc实例在登录页都会有这个外链
https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/4eef81401ea38529b628cb6d5cf9aa78dd094670/templates/navi.php#L102

lovelive.us这个域有人（771644051@qq.com）持有着，但没有设a记录：
https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/4eef81401ea38529b628cb6d5cf9aa78dd094670/templates/navi.php#L69
https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/4eef81401ea38529b628cb6d5cf9aa78dd094670/lib/ui.php#L19

所有对stusgame.com的提及见https://github.com/MoeNetwork/Tieba-Cloud-Sign/search?q=stusgame.com

**Comment by ak-tequila** [comment]
那请问后续更新会考虑将这个链接改到现在的github上吗，就是现在这个Repository上？
我的网站我可以自行更改，但用docker-compose不太方便。
感谢答复。

**Comment by kenvix** [comment]
已修复
