### ISSUE TITLE
关于更新的问题

### ISSUE THREAD

**Issue by EvolvedGhost** [MoeNetwork/Tieba-Cloud-Sign#148]
首先使用内置检查更新的功能已经无法使用，因为master/ajax.php第89行的
`$c = new wcurl('http://kenvix.oschina.io/tieba-cloud-sign/');`
已经无法使用http访问，但是可以使用https访问，即
`$c = new wcurl('https://kenvix.oschina.io/tieba-cloud-sign/');`

但是我注意到Gitee上的贴吧签到已经处于Archived状态，并且我不确定是否只剩下手动更新的方法使用，因为即使我改为后者成功获取到更新信息也不能同步到Github上最新的版本，并且仍然显示为老旧的4.8版本。

请问自动更新功能是否已经停用，只能手动更新？如果说已经停用的话，有没有计划重置自动更新功能，能否增加类似于`https://ghproxy.com/` 的Github反代更新？

**Comment by BANKA2017** [comment]
目前自动更新确实无法正常使用，至于重置自动更新这个嘛，社区有人pr就能搞起来了

**Comment by kenvix** [comment]
实现自动更新不算复杂，主要是没人做。重做这个功能的步骤是：

1. 编写 Github Action 配置文件，产生 Push 事件时扫描仓库文件并生成文件清单
2. 将此清单文件发布到一个地方，例如另一个 github 仓库
3. 修改程序指向此清单的发布位置

此外：
- 在容器内运行时应自动禁用自动更新，或者模仿 NextCloud Server 那样解压数据到挂载点再运行，确保程序文件持久化

**Comment by n0099** [comment]
国内服tx云活动小鸡能不能访问github都是问题

**Comment by BANKA2017** [comment]
最新的版本尝试使用GitHub的commit列表解决更新问题，但境内机器就不好说了 #169
