### ISSUE TITLE
您的 BDUSS Cookie 信息有误，请核验后重新绑定

### ISSUE THREAD

**Issue by YoRHa-ANOHANA** [MoeNetwork/Tieba-Cloud-Sign#151]
百度账号管理-手动绑定 出现这报错。昨天还能使用 今天就不行了  没有安装其他插件。扫码登录网页授权都不能使用

**Comment by YoRHa-ANOHANA** [comment]
![QQ截图20220401142348](https://user-images.githubusercontent.com/32413484/161206938-de604695-5b71-432b-8010-ac1423e7399e.png)

**Comment by n0099** [comment]
@BANKA2017

**Comment by n0099** [comment]
![](https://user-images.githubusercontent.com/13030387/161299130-6d39b478-9655-4036-b00e-e56d9e6e6593.png)
![](https://user-images.githubusercontent.com/13030387/161299221-68f5ce18-91f1-4232-8945-35c697655ab4.png)
https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/c9aa42544d1ed3d73c0f7cc3cef252d48b22f3f5/lib/class.misc.php#L196-L198

**Comment by n0099** [comment]
https://github.com/MoeNetwork/Tieba-Cloud-Sign/commit/c491713d280ab3fec27f05c3f7df9e8adc0e2341#diff-d744da432aca895bafdec105e28f2ea680affd1681ac2de8a674fc461b57b762R99
是接口https://tieba.baidu.com/mg/o/profile?format=json 的问题？

**Comment by n0099** [comment]
https://github.com/MoeNetwork/Tieba-Cloud-Sign/commit/c491713d280ab3fec27f05c3f7df9e8adc0e2341#diff-d744da432aca895bafdec105e28f2ea680affd1681ac2de8a674fc461b57b762R99
是接口https://tieba.baidu.com/mg/o/profile?format=json 的问题？

**Comment by Starry-OvO** [comment]
> [c491713#diff-d744da432aca895bafdec105e28f2ea680affd1681ac2de8a674fc461b57b762R99](https://github.com/MoeNetwork/Tieba-Cloud-Sign/commit/c491713d280ab3fec27f05c3f7df9e8adc0e2341#diff-d744da432aca895bafdec105e28f2ea680affd1681ac2de8a674fc461b57b762R99) 是接口https://tieba.baidu.com/mg/o/profile?format=json 的问题？

目前有几个可以校验bduss可用性的活跃接口，活跃指日均访问量较大
1、http://tieba.baidu.com/f/user/json_userinfo
网页端应该经常用
需要bduss做cookies
2、http://c.tieba.baidu.com/c/s/login
app经常用，访问量巨大
需要_client_version和bdusstoken两个字段，然后用tiebaclient!!!签名，最后form表单post
3、http://c.tieba.baidu.com/c/s/initNickname
app经常用，访问量巨大
需要_client_version和BDUSS两个字段，然后用tiebaclient!!!签名，最后form表单post

**Comment by BANKA2017** [comment]
取得用户信息的接口现在还需要填写 `STOKEN`，目前版本的云签还不支持保存 `STOKEN`
https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/1cc87cb7116aee8d997ed6cf6bfc6f9bc45b8a5c/lib/sfc.functions.php#L98-L109

一并失效的还有同样使用这个接口的 检查bduss有效性 插件
