### ISSUE TITLE
刷新贴吧列表无效

### ISSUE THREAD

**Issue by SeanChengN** [MoeNetwork/Tieba-Cloud-Sign#153]
手动更新了早上最新的commits，BDUSS重新绑定了，但是列表无法刷新
![chrome_Ki6CaO8RKv](https://user-images.githubusercontent.com/20624068/161363226-7c9d7ed9-26c0-46cc-86c5-0b12641c223f.png)

**Comment by BANKA2017** [comment]
这个刷新贴吧列表的接口遇到的问题跟早上修复的那个一样，需要 `STOKEN`，但云签没提供

**Comment by BANKA2017** [comment]
虽然还没测试，我估计网页签到的接口也一并失效了

**Comment by n0099** [comment]
#151
