### ISSUE TITLE
直接安装的签到，没用docker，手动绑定BDUSS失败，提示：您的 BDUSS Cookie 信息有误，请核验后重新绑定

### ISSUE THREAD

**Issue by hou-solifugus** [MoeNetwork/Tieba-Cloud-Sign#154]
您好，直接使用源码安装的系统，没有使用docker。
安装完成后，使用手动绑定BDUSS，提示：您的 BDUSS Cookie 信息有误，请核验后重新绑定
一直失败，使用扫码绑定最后提示undefer。
但是同样的BDUSS在其他的签到系统上就能绑定成功。

**Comment by BANKA2017** [comment]
想了半天想到一种可能，绑定的帐号是那种用直接用手机注册，没有设定百度id的，因为取得的百度id为空白导致绑定失败

https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/e13aa6ee7b3c0265d2980da7a5150b98a04c2a5a/setting.php#L489-L492

**Comment by cs-xiao** [comment]
我试了几个签到系统 4.9.5/6都不行 之前是可以绑上的。。。

**Comment by kenvix** [comment]
Docker镜像的构建有问题，目前的镜像不是最新版本。待修复。

**Comment by hou-solifugus** [comment]
> Docker镜像的构建有问题，目前的镜像不是最新版本。待修复。

好的，感谢，我等等再部署
