### ISSUE TITLE
使用docker方式部署，手动绑定BDUSS失败，提示：您的 BDUSS Cookie 信息有误，请核验后重新绑定

### ISSUE THREAD

**Issue by feilewu** [MoeNetwork/Tieba-Cloud-Sign#155]
你好，使用docker方式部署，一开始，扫码登录，手机显示扫码成功，页面卡住不动，然后使用手动绑定的方式，获取到BDUSS后，手动输入后，提示如标题所示的错误（没有使用其他任何插件）

之前没有问题，重装后绑定出问题的，应该和百度账号无关

**Comment by Cloudy-Kumori** [comment]
你好，我也有同样的问题，我扫码登录后会提示绑定成功，绑定的账号显示为undefined，之后刷新页面其实还是没有绑定上的。同一个账号之前是可以绑定的，但是无法更新bduss

**Comment by xiaoyaoz1** [comment]
>同遇到，我还以为搭建错了~~~

**Comment by yydlh** [comment]
我是源码安装的，升级到4.96就可以了。

**Comment by spellyaohui** [comment]
> 我是源码安装的，升级到4.96就可以了。

确实手动更新源码好使了,谢啦!

**Comment by BANKA2017** [comment]
> > > 我是源码安装的，升级到4.96就可以了。
> > 
> > 
> > 确实手动更新源码好使了,谢啦!
> 
> docker下怎么更新源码呢？

请参考 https://github.com/MoeNetwork/Tieba-Cloud-Sign/issues/115#issuecomment-884139684
