### ISSUE TITLE
Possible XSS vulnerability

### ISSUE THREAD

**Issue by enferas** [MoeNetwork/Tieba-Cloud-Sign#156]
Hello,

I would like to report for XSS vulnerability.

In file https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/master/templates/control.php line 53.

```php
case 'setplug':
  $plug = strip_tags($_GET['plug']);
  $pluginfo = getPluginInfo($plug);
```

Then, there is an echo in line 62.
```php
echo '<a href="'.$pluginfo['plugin']['url'].'" target="_blank">';
```

strip_tags is not secure in this case. If you can look to this code example the alert will be printed when you press on the link.
```php
<?php
$x = "'javascript:alert()'";
$y = strip_tags($x);
echo "<a href=$x>ClickMe</a>";
```

**Comment by BANKA2017** [comment]
https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/e13aa6ee7b3c0265d2980da7a5150b98a04c2a5a/templates/control.php#L23

https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/e13aa6ee7b3c0265d2980da7a5150b98a04c2a5a/lib/plugins.php#L197-L199

这是一个没有想象中严重的漏洞，我们在前面设置了权限检查挡住了非admin用户的访问，此外文件存在性检查会确保不存在的插件不会被加载，因此触发这个漏洞的需要：
- 用户为**管理员**
- 使用了带有恶意外部链接的插件

**感谢您的反馈，我们将会在晚些时候进行修复**

-----
*translated by deepl.com*

https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/e13aa6ee7b3c0265d2980da7a5150b98a04c2a5a/templates/control.php#L23 

https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/e13aa6ee7b3c0265d2980da7a5150b98a04c2a5a/lib/plugins.php#L197-L199

This is not as serious a vulnerability as you might think, we set up a permission check earlier to block access by non-admin users, in addition the file existence check will ensure that non-existent plugins will not be loaded, so two conditions are required to trigger this vulnerability

- The user is an **administrator**
- A plugin with a malicious url is used

**Thank you for your feedback, we will fix it later**

**Comment by RiotGamesU** [comment]
> https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/e13aa6ee7b3c0265d2980da7a5150b98a04c2a5a/templates/control.php#L23
> 
> https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/e13aa6ee7b3c0265d2980da7a5150b98a04c2a5a/lib/plugins.php#L197-L199
> 
> 这是一个没有想象中严重的漏洞，我们在前面设置了权限检查挡住了非admin用户的访问，此外文件存在性检查会确保不存在的插件不会被加载，因此触发这个漏洞的需要：
> 
> * 用户为**管理员**
> * 使用了带有恶意外部链接的插件
> 
> **感谢您的反馈，我们将会在晚些时候进行修复**
> 
> _translated by deepl.com_
> 
> https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/e13aa6ee7b3c0265d2980da7a5150b98a04c2a5a/templates/control.php#L23
> 
> https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/e13aa6ee7b3c0265d2980da7a5150b98a04c2a5a/lib/plugins.php#L197-L199
> 
> This is not as serious a vulnerability as you might think, we set up a permission check earlier to block access by non-admin users, in addition the file existence check will ensure that non-existent plugins will not be loaded, so two conditions are required to trigger this vulnerability
> 
> * The user is an **administrator**
> * A plugin with a malicious url is used
> 
> **Thank you for your feedback, we will fix it later**

礼貌问询deepl.com中译英和英译中效果怎么样

**Comment by n0099** [comment]
> 礼貌问询deepl.com中译英和英译中效果怎么样

您已经看到了

**Comment by n0099** [comment]
This is the first CVE assigned to tc in its seven years history.
