### ISSUE TITLE
docker搭建在本地内网提示错误，无法正确显示验证码，绑定账号提示错误

### ISSUE THREAD

**Issue by Charlie-can** [MoeNetwork/Tieba-Cloud-Sign#159]
BDUSS Cookie已经确认无误
仍然提示错误

**Comment by Charlie-can** [comment]
![QQ截图20220409003013](https://user-images.githubusercontent.com/45510526/162484003-0ed0659f-4050-48df-9eb3-bc4ba28d3e61.png)
![QQ截图20220409002724](https://user-images.githubusercontent.com/45510526/162484015-860d5fef-a969-4387-a5d0-1e8164301aaa.png)
![QQ截图20220409003027](https://user-images.githubusercontent.com/45510526/162484020-1978fd69-5247-4a6b-ba83-ff8375a1b68d.png)

**Comment by BANKA2017** [comment]
docker构建的不是最新版本
https://github.com/MoeNetwork/Tieba-Cloud-Sign/issues/154#issuecomment-1086765650
请参考以下链接更新版本
https://github.com/MoeNetwork/Tieba-Cloud-Sign/issues/115#issuecomment-884139684

**Comment by Charlie-can** [comment]
> 
感谢回复，已经更新最新版本4.96了，可以正常登陆百度账户，但是验证码还是无法正常显示，使用自带的检测更新依然显示更新失败

**Comment by Charlie-can** [comment]
但是后台仍然显示
![image](https://user-images.githubusercontent.com/45510526/162564701-79c22a66-9ef4-4a6f-8033-567a611181b6.png)

**Comment by BANKA2017** [comment]
> > 
> 
> 感谢回复，已经更新最新版本4.96了，可以正常登陆百度账户，但是验证码还是无法正常显示，使用自带的检测更新依然显示更新失败

- 自带的检查更新目前确实是不行的，详细追踪请看 #148 
-  没法生成验证码的问题请检查是否安装了 `php-gd` 库

**Comment by BANKA2017** [comment]
> 但是后台仍然显示 ![image](https://user-images.githubusercontent.com/45510526/162564701-79c22a66-9ef4-4a6f-8033-567a611181b6.png)

这堆 `HTTP 499` 应该是这个 `do.php` 执行时间太长直接断开了，问题应该不是很大

**Comment by BANKA2017** [comment]
> > > 
> > 
> > 
> > 感谢回复，已经更新最新版本4.96了，可以正常登陆百度账户，但是验证码还是无法正常显示，使用自带的检测更新依然显示更新失败
> 
> * 自带的检查更新目前确实是不行的，详细追踪请看 [关于更新的问题 #148](https://github.com/MoeNetwork/Tieba-Cloud-Sign/issues/148)
> * 没法生成验证码的问题请检查是否安装了 `php-gd` 库

我再次检查发现是docker镜像缺少一个叫 `php7-session` 的包，导致无法使用 `session_start()` 函数，我对 docker 不太熟悉，暂时也没法打包，您可以尝试进去用bash运行 `apk add php7-session`，也许会有用

**Comment by Charlie-can** [comment]
再重启之后就显示：
“连接数据库失败，请检查数据库信息。错误编号：2002”
![image](https://user-images.githubusercontent.com/45510526/162603116-7710b0eb-aef8-424d-afab-83054d4d8c19.png)
这是我第一次重启

之后又重新创建了一个容器，重启后也是相同的状态

我跟着提示修改mysql_aotoload.php的强制连接
![image](https://user-images.githubusercontent.com/45510526/162603131-aa586401-fc16-4ea6-826f-e1913df69631.png)
之后显示：
服务器PHP不支持MySql数据库
![image](https://user-images.githubusercontent.com/45510526/162603139-defe9576-a263-4b20-8830-23cc5987f7ac.png)

**Comment by Charlie-can** [comment]
数据库是使用的mysql5.7.9
使用管理软件Navicat可以正常使用数据库

**Comment by BANKA2017** [comment]
首先，请回退第二项修改，docker版本请继续使用mysqli
然后，请打开 `/config.php` 文件，将数据库地址的  `127.0.0.1` 修改为 `db:3306`
```php
//修改前
define('DB_HOST','127.0.0.1');
//修改后
define('DB_HOST','db:3306');
```

**Comment by Charlie-can** [comment]
抱歉，前几天没空，没有及时回复
看到有更新后我重新拉去了一个新的镜像，在新镜像里问题已经解决并成功运行
