### ISSUE TITLE
执行do.php，执行时间比较久，最后反馈502或者301

### ISSUE THREAD

**Issue by hou-solifugus** [MoeNetwork/Tieba-Cloud-Sign#163]
----------------------------------------------------------------------------
★[2022-04-15 07:30:03] Successful
----------------------------------------------------------------------------
<html>

<head><title>301 Moved Permanently</title></head>

<body>

<center><h1>301 Moved Permanently</h1></center>

<hr><center>nginx</center>

</body>

</html>

----------------------------------------------------------------------------
★[2022-04-15 08:00:01] Successful
----------------------------------------------------------------------------
<html>

<head><title>502 Bad Gateway</title></head>

<body>

<center><h1>502 Bad Gateway</h1></center>

<hr><center>nginx</center>

</body>

</html>

----------------------------------------------------------------------------
★[2022-04-15 08:13:30] Successful
----------------------------------------------------------------------------
<html>

<head><title>502 Bad Gateway</title></head>

<body>

<center><h1>502 Bad Gateway</h1></center>

<hr><center>nginx</center>

</body>

</html>

----------------------------------------------------------------------------
★[2022-04-15 08:31:51] Successful
----------------------------------------------------------------------------
<html>

<head><title>502 Bad Gateway</title></head>

<body>

<center><h1>502 Bad Gateway</h1></center>

<hr><center>nginx</center>

</body>

</html>

----------------------------------------------------------------------------
★[2022-04-15 09:01:51] Successful
----------------------------------------------------------------------------
<html>

<head><title>502 Bad Gateway</title></head>

<body>

<center><h1>502 Bad Gateway</h1></center>

<hr><center>nginx</center>

</body>

</html>

----------------------------------------------------------------------------
★[2022-04-15 09:31:51] Successful
----------------------------------------------------------------------------

**Comment by kenvix** [comment]
正常现象。只要确实执行了签到即可

**Comment by hou-solifugus** [comment]
修改了配置参数，已解决
