### ISSUE TITLE
4.97版本无法登陆，扫码跟手动都报错。

### ISSUE THREAD

**Issue by iiidcc** [MoeNetwork/Tieba-Cloud-Sign#165]
百度贴吧云签到 V4.97 (PHP 7.0.33) 在工作时发生致命的异常 @ 2022-05-09 01:40:17
消息：#10000 - MySQL 语句执行错误：
语句：INSERT INTO `我的网址`.`tc_baiduid` (`uid`,`bduss`,`name`,`portrait`) VALUES (1, '我的CK, '我的ID', '我的portrait')
错误：#1054 - Unknown column 'portrait' in 'field list'

**Comment by BANKA2017** [comment]
https://github.com/MoeNetwork/Tieba-Cloud-Sign/issues/162#issuecomment-1097664576

**Comment by iiidcc** [comment]
> [#162 (comment)](https://github.com/MoeNetwork/Tieba-Cloud-Sign/issues/162#issuecomment-1097664576)
已经执行了这个文件提示我


您的云签到已升级到 V4.97 版本，请勿重复更新

请立即删除 /setup/update4.96to4.97.php

**Comment by BANKA2017** [comment]
> > [#162 (comment)](https://github.com/MoeNetwork/Tieba-Cloud-Sign/issues/162#issuecomment-1097664576)
> > 已经执行了这个文件提示我
> 
> 您的云签到已升级到 V4.97 版本，请勿重复更新
> 
> 请立即删除 /setup/update4.96to4.97.php

那尝试把这三行删掉再执行一遍？

https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/d408fa6215c29bfb0c0f9a71d4a22364a1ff8745/setup/update4.96to4.97.php#L9-L11

**Comment by iiidcc** [comment]
> 

警告curl_close(): supplied resource is not a valid cURL handle resource目录的lib/class.wcurl.php @ 222行

**Comment by BANKA2017** [comment]
能跑到curl报警告说明数据库的表已经更新好了

那现存的帐号能显示portrait了吗，能显示就说明没问题了

**Comment by iiidcc** [comment]
> 能跑到curl报警告说明数据库的表已经更新好了
> 
> 那现存的帐号能显示portrait了吗，能显示就说明没问题了

更新完了以后重启服务器可以了谢谢大佬指点！！！
