### ISSUE TITLE
无法绑定百度账号

### ISSUE THREAD

**Issue by 623524718** [MoeNetwork/Tieba-Cloud-Sign#168]
使用百度贴吧app扫码显示“成功绑定百度账号：undefined”
使用教程获取BDUSS方法显示“您的 BDUSS Cookie 信息有误，请核验后重新绑定”

**Comment by BANKA2017** [comment]
- 检查版本号是不是4.97
- 参考 #162 ，检查是不是跨多个版本升级后没执行升级脚本

如果还是不行请继续回复

**Comment by 623524718** [comment]
> 

解决了，版本号问题，之前是4.95，更新下就好了
