### ISSUE TITLE
#10000 - MySQL 语句执行错误：

### ISSUE THREAD

**Issue by xiangwanavava** [MoeNetwork/Tieba-Cloud-Sign#171]
![image](https://user-images.githubusercontent.com/92348460/170871435-69b98424-c77a-4390-a5ac-d0981ec56cb6.png)

绑定百度账号时绑定不了

**Comment by xiangwanavava** [comment]
使用扫码/网页登录则会提示“操作失败，未知错误。这可能是网络原因所致，请刷新重试#2”

**Comment by BANKA2017** [comment]
https://github.com/MoeNetwork/Tieba-Cloud-Sign/commit/213e7467acff0ea1e8dcc83b289607e3dea1580d#commitcomment-74566038

**Comment by xiangwanavava** [comment]
> 

感谢

**Comment by xiangwanavava** [comment]
> [213e746#commitcomment-74566038](https://github.com/MoeNetwork/Tieba-Cloud-Sign/commit/213e7467acff0ea1e8dcc83b289607e3dea1580d#commitcomment-74566038)
> 
> > 跨多个版本升级后请先后执行 4.96to4.97.php 与 4.97to4.98.php
 请问这两个文件在哪里呢

**Comment by BANKA2017** [comment]
> > [213e746#commitcomment-74566038](https://github.com/MoeNetwork/Tieba-Cloud-Sign/commit/213e7467acff0ea1e8dcc83b289607e3dea1580d#commitcomment-74566038)
> > > 跨多个版本升级后请先后执行 4.96to4.97.php 与 4.97to4.98.php
> > > 请问这两个文件在哪里呢

`/setup` 文件夹里面
