### ISSUE TITLE
后台显示签到，实际上贴吧没有签到

### ISSUE THREAD

**Issue by mxg996** [MoeNetwork/Tieba-Cloud-Sign#172]
![E4DBF4FB-D738-4655-B526-F1BD70B7616A](https://user-images.githubusercontent.com/74495030/170888923-f0b2d1f5-d96e-4a30-9a6b-138d8fe069f2.png)

现在就是出现网站运行正常，百度贴吧不能正常签到，不知道哪里出了问题。

**Comment by kenvix** [comment]
请升级到最新版本
