### ISSUE TITLE
检测到无 install.lock 文件

### ISSUE THREAD

**Issue by Noplch0** [MoeNetwork/Tieba-Cloud-Sign#177]
![image](https://user-images.githubusercontent.com/95165748/179902035-e5e69264-55db-41e8-85fe-67fd9a30c6cc.png)

**Comment by kenvix** [comment]
自行创建一个即可

**Comment by Noplch0** [comment]
> 自行创建一个即可

/setup在哪里，我找不到

**Comment by kenvix** [comment]
你手动创建这个文件夹即可

**Comment by Noplch0** [comment]
> 你手动创建这个文件夹即可

在哪里创建，我在yml文件目录下创建了文件夹和.lock文件仍然提示

**Comment by L2ncE** [comment]
请问解决问题了吗，我也遇到了相同问题。到底是在哪里添加呢

**Comment by kenvix** [comment]
最新版本应该是能自动建立lock文件的
