### ISSUE TITLE
当使用浏览器扩展CleanURLs时无法刷新贴吧列表

### ISSUE THREAD

**Issue by n0099** [MoeNetwork/Tieba-Cloud-Sign#179]
- [x] 我已升级贴吧云签到到最新版本，并且运行了升级脚本
- [x] 我已搜索过 Issue 区，没有找到相关问题

# 问题描述

刷新贴吧列表的api url是`setting.php?mod=showtb&ref`
https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/213e7467acff0ea1e8dcc83b289607e3dea1580d/setting.php#L550-L551
而CleanURLs最近引入了一个规则以删除所有的ref参数：https://github.com/ClearURLs/Addon/issues/179 https://github.com/ClearURLs/Addon/issues/153
这导致该请求会被CleanURLs删除掉`&ref`部分从而无法刷新贴吧列表

# 复现步骤

1. 安装浏览器扩展[CleanURLs](https://github.com/ClearURLs/Addon)
1. 在`index.php?mod=showtb`点击`刷新贴吧列表`
2. 观察f12-network可见response永远处于pending：
  ![image](https://user-images.githubusercontent.com/13030387/182008585-23ce0a87-103f-46e0-bda9-e29006bdca4c.png)
  但详细信息里又有response：
  ![image](https://user-images.githubusercontent.com/13030387/182008621-7e587a76-e6ee-498c-a84a-b552dd7279ca.png)
  ![image](https://user-images.githubusercontent.com/13030387/182008633-563cacc4-f30b-43a6-92e2-7cede9c042a1.png)

# 环境

 - 云签到版本：4.98.0
 - 服务器系统和版本：Ubuntu 2204
 - 云签到是否在 Docker 中运行：否
 - PHP 版本：8.1.8
 - MySQL 版本：8.0.29

**Comment by BANKA2017** [comment]
有必要修改名称以规避这种问题
