### ISSUE TITLE
无法使用 手动绑定 的方式绑定 百度账号

### ISSUE THREAD

**Issue by Steven52065** [MoeNetwork/Tieba-Cloud-Sign#183]
- [x] 我已升级贴吧云签到到最新版本，并且运行了升级脚本
- [x] 我已搜索过 Issue 区，没有找到相关问题

# 问题描述

1. passport.baidu.com -> Cookie 下面只有STOKEN,而没有BDUSS。baidu.com -> Cookie 下面有BDUSS
2. 将1.中的STOKEN和BDUSS填入后，报错
![image](https://user-images.githubusercontent.com/36119581/183616782-780b5030-ec66-4da0-9f57-fe42e412ec7c.png)

# 复现步骤

使用docker-compose安装后，在  检查更新 处，使用  GitHub更新服务器  更新
chrome，打开baidu.com,点击地址栏左侧的“🔒”，打开“Cookie”，无法在passport.baidu.com -> Cookie 下面找到BDUSS
添加passport.baidu.com -> Cookie 下面的 BDUSS 和 baidu.com -> Cookie 下面的BDUSS，报错

# 环境

 - 云签到版本：V5.00
 - 服务器系统和版本：Ubuntu 22.04 LTS (GNU/Linux 5.15.0-41-generic x86_64)
 - 云签到是否在 Docker 中运行：是
 - PHP 版本：7.4.22
 - MySQL 版本：MySQLi  可用

**Comment by BANKA2017** [comment]
估计是跨越了多个版本升级导致升级脚本未能执行升级，请参考下面两个回复手动处理
https://github.com/MoeNetwork/Tieba-Cloud-Sign/issues/174#issuecomment-1173344589 https://github.com/MoeNetwork/Tieba-Cloud-Sign/issues/174#issuecomment-1173433609

**Comment by BANKA2017** [comment]
- 根据截图来看，导致出错是因为数据表缺少 `portrait` 列，而不是 `stoken` 的问题

- 另外 `stoken` 不是这样获取的，百度各项服务之间的 `stoken` 并不互通，请到 `tieba.baidu.com` 域下取 `stoken` 用于云签登录

**Comment by Steven52065** [comment]
![image](https://user-images.githubusercontent.com/36119581/183644411-c1451a0e-b2ee-449f-8951-3c34f0ce8b25.png)
照着那个来了两遍（弄完一次，不行，删除了重新创建容器），报错变了...
这次用的是https://tieba.baidu.com/index.html网址下，baidu.com域下的BDUSS；tieba.baidu.com域下的STOKEN，这样对么？


![image](https://user-images.githubusercontent.com/36119581/183644968-8840d8fc-4a76-427f-bdc2-05229068dcf2.png)
扫码也提示错误

**Comment by BANKA2017** [comment]
> 照着那个来了两遍（弄完一次，不行，删除了重新创建容器），报错变了... 这次用的是[https://tieba.baidu.com/index.html网址下，baidu.com域下的BDUSS；tieba.baidu.com域下的STOKEN，这样对么？](https://tieba.baidu.com/index.html%E7%BD%91%E5%9D%80%E4%B8%8B%EF%BC%8Cbaidu.com%E5%9F%9F%E4%B8%8B%E7%9A%84BDUSS%EF%BC%9Btieba.baidu.com%E5%9F%9F%E4%B8%8B%E7%9A%84STOKEN%EF%BC%8C%E8%BF%99%E6%A0%B7%E5%AF%B9%E4%B9%88%EF%BC%9F)
> 
> ![image](https://user-images.githubusercontent.com/36119581/183644968-8840d8fc-4a76-427f-bdc2-05229068dcf2.png) 扫码也提示错误

你这条回复暴露bduss了，我给你删了，另外建议改密码使那个bduss失效，避免被人利用

要解决这个很简单，只要前往 管理菜单-工具箱-运行sql语句 运行一下下面这行
```
ALTER TABLE `{VAR-PREFIX}baiduid` ADD `stoken` TEXT NULL DEFAULT NULL AFTER `bduss`;
```

**Comment by n0099** [comment]
> 我给你删了
edit comment history里还有

**Comment by kenvix** [comment]
> > 我给你删了
> 
> edit comment history里还有

那就再登出下就没了

**Comment by n0099** [comment]
不登录也能看到edit history

**Comment by kenvix** [comment]
> 不登录也能看到edit history

我指的是登出这个bduss

**Comment by n0099** [comment]
请 @Steven52065 登出bduss或者改密（可以再改回来
