### ISSUE TITLE
nginx反代后无法刷新贴吧列表

### ISSUE THREAD

**Issue by Pollo3470** [MoeNetwork/Tieba-Cloud-Sign#185]
# 问题描述
使用nginx反代，访问管理页面，点击刷新列表会一直卡在正在刷新的状态

# 复现步骤
nginx反代访问网页管理界面，点击刷新贴吧列表

# 环境
docker-compose

 - 云签到版本：V5.00
 - 服务器系统和版本：Linux f0c63247b6fc 5.19.0-trunk-amd64 '#'1 SMP PREEMPT_DYNAMIC Debian 5.19-1~exp1 (2022-08-02) x86_64
 - 云签到是否在 Docker 中运行：是
 - PHP 版本：8.0.21 非线程安全
 - MySQL 版本：10.6.8-MariaDB-log

**Comment by n0099** [comment]
https://github.com/MoeNetwork/Tieba-Cloud-Sign/issues/179

**Comment by Pollo3470** [comment]
找到原因了，是CSRF防御导致的，在站点设置里改为反代域名即可
