### ISSUE TITLE
你好请问吧务的插件在哪里下载 插件库里没又看到云封禁之类的差价

### ISSUE THREAD

**Issue by mnwgkj** [MoeNetwork/Tieba-Cloud-Sign#192]

**Comment by n0099** [comment]
都是ver4以前做的插件，后来由@KDNIL 维护：https://github.com/96dl/Tieba-Cloud-Sign-Plugins

**Comment by kenvix** [comment]
我觉得可以把所有插件都直接合并到主线plugins文件夹，方便使用的同时也能有效减少此类疑问
