### ISSUE TITLE
当前共有 12 个计划任务，您需要添加根目录下 do.php 到您主机的计划任务后，下面的任务才能被执行

### ISSUE THREAD

**Issue by mnwgkj** [MoeNetwork/Tieba-Cloud-Sign#195]
当前共有 12 个计划任务，您需要添加根目录下 do.php 到您主机的计划任务后，下面的任务才能被执行
请问这个需要配置吗
具体是配置到宝塔计划还是贴吧签到管理后台计划可否详细些
![image](https://user-images.githubusercontent.com/109659250/188960014-a5df3cd0-6d88-4437-8a28-369b6986d5c1.png)
目前有漏签不知道怎么回事

**Comment by mnwgkj** [comment]
是签到需要间隔多少毫秒？ 我设置的是0

**Comment by L2ncE** [comment]
配置到宝塔面板的计划任务 php do.php即可

**Comment by BANKA2017** [comment]
> 是签到需要间隔多少毫秒？ 我设置的是0

`0` 即可，一般都不会有什么问题，即使签到过快后面也会有重签兜着

> 具体是配置到宝塔计划还是贴吧签到管理后台计划可否详细些

到宝塔的计划任务面板，挨个填

```
任务类型：Shell脚本
任务名称：这个随便填，只是方便你找到这个任务
执行周期：N分钟  1分钟
脚本内容：php 你do.php所在的目录/do.php
```

**Comment by n0099** [comment]
crontab -e
https://crontab.guru
