### ISSUE TITLE
关于宝塔面板或服务器重启后会自启动吗

### ISSUE THREAD

**Issue by mnwgkj** [MoeNetwork/Tieba-Cloud-Sign#196]
问题1，关于宝塔面板或服务器重启后会自动启动吗？
问题2，每月的吧务考核是否有对应的插件，或者多开发几个吧务的插件，

**Comment by BANKA2017** [comment]
1. 不会
2. 没有，你可以循环封人实现这一需求，如果没人要封可以封不介意者的号

**Comment by mnwgkj** [comment]
宝塔自动启动需要如何配置呢

**Comment by BANKA2017** [comment]
> 宝塔自动启动需要如何配置呢

不需要配置，默认如此

**Comment by mnwgkj** [comment]
好的谢谢

**Comment by n0099** [comment]
> 2. 没有，你可以循环封人实现这一需求，如果没人要封可以封不介意者的号

可以封自己
