### ISSUE TITLE
刷新贴吧列表无效

### ISSUE THREAD

**Issue by NNanfeng** [MoeNetwork/Tieba-Cloud-Sign#206]
- [x] 我已升级贴吧云签到到最新版本，并且运行了升级脚本
- [x] 我已搜索过 Issue 区，没有找到相关问题

# 问题描述

![QQ截图20220913162541](https://user-images.githubusercontent.com/92158315/189851808-96a2536f-32a7-4ac6-84cb-51a563f168a5.png)

# 复现步骤
在此之前 这个用户删除了自己的绑定信息 然后进行了重新绑定，之后就出现了刷新贴吧列表还是零个的现象

# 环境

 - 云签到版本：百度贴吧云签到 V5.00 
 - 服务器系统和版本：Ubuntu 20.04.4 LTS x86_64(Py3.7.9)
 - 云签到是否在 Docker 中运行：否
 - PHP 版本：PHP 7.0
 - MySQL 版本：MySQL 5.6.50

**Comment by BANKA2017** [comment]
这个问题在 #186 #205 有出现，请尝试按照 #205 的回答的流程走一遍看看是不是 `stoken` 的问题

**Comment by NNanfeng** [comment]
![image](https://user-images.githubusercontent.com/92158315/189879875-1f53ea5f-7ec6-4bd2-8d3f-f68da67668cb.png)
按照其中一个手动添加的方法，点击提交之后直接出线乱码

**Comment by NNanfeng** [comment]
![image](https://user-images.githubusercontent.com/92158315/189881031-0223553d-7321-417a-a58f-f40a33761c9e.png)
在服务器上执行那个接口也能正确的获得返回值

**Comment by n0099** [comment]
> ![image](https://user-images.githubusercontent.com/92158315/189879875-1f53ea5f-7ec6-4bd2-8d3f-f68da67668cb.png) 按照其中一个手动添加的方法，点击提交之后直接出线乱码

什么gbk

**Comment by kenvix** [comment]
> ![image](https://user-images.githubusercontent.com/92158315/189879875-1f53ea5f-7ec6-4bd2-8d3f-f68da67668cb.png) 按照其中一个手动添加的方法，点击提交之后直接出线乱码

卸了gzip插件

**Comment by n0099** [comment]
> > ![image](https://user-images.githubusercontent.com/92158315/189879875-1f53ea5f-7ec6-4bd2-8d3f-f68da67668cb.png) 按照其中一个手动添加的方法，点击提交之后直接出线乱码
> 
> 卸了gzip插件

https://github.com/MoeNetwork/Tieba-Cloud-Sign/pull/193#discussion_r965069862

**Comment by NNanfeng** [comment]
卸载gzip插件后出现如下报错
![image](https://user-images.githubusercontent.com/92158315/190260510-d0d4280f-285d-4924-9f42-9151cbff83a9.png)

**Comment by n0099** [comment]
> 卸载gzip插件后出现如下报错 ![image](https://user-images.githubusercontent.com/92158315/190260510-d0d4280f-285d-4924-9f42-9151cbff83a9.png)

https://github.com/MoeNetwork/Tieba-Cloud-Sign/issues/162

**Comment by NNanfeng** [comment]
![image](https://user-images.githubusercontent.com/92158315/190272926-9b68df08-8686-4bda-9eca-087f64cbd1c6.png)

**Comment by NNanfeng** [comment]
我将php文件里的语句执行之后出现如下报错
![image](https://user-images.githubusercontent.com/92158315/190273386-fa84e68d-2615-47fa-86ea-67e6b3741c43.png)

**Comment by NNanfeng** [comment]
然后手动执行了update4.97to4.98.php里的语句，所有问题得到解决，感谢回答
