### ISSUE TITLE
docker重启后，出现2002错误。请问 mysql_autoload.php怎么找到这个文件改强制连接

### ISSUE THREAD

**Issue by 7161457** [MoeNetwork/Tieba-Cloud-Sign#213]
你好，我是docker pull moenetwork/tieba-cloud-sign 拉出来的镜像程序，然后启动后连接自己搭建的mariadb数据库，已经部署成功了，并且正常签到。
由于主机断电导致docker程序重启后，出现连接数据库失败，经测试数据库是正常，我看需要开启 MySQL 连接方式强制功能，要打开 mysql_autoload.php，
请问 mysql_autoload.php怎么找到这个文件。我是群辉nas。

**Comment by n0099** [comment]
#215
