### ISSUE TITLE
手动执行do，只签到20个贴吧

### ISSUE THREAD

**Issue by fateplayer** [MoeNetwork/Tieba-Cloud-Sign#230]
- [x] 我已升级贴吧云签到到最新版本，并且运行了升级脚本
- [x] 我已搜索过 Issue 区，没有找到相关问题

# 问题描述

手动执行do，只签到20个贴吧，定时任务未测试

# 复现步骤

4次手动执行网页根目录do.php，均只签到20个贴吧。贴吧列表之前已刷新

# 环境

 - 云签到版本：5.00
 - 服务器系统和版本：rockylinux 8.5
 - 云签到是否在 Docker 中运行：否
 - PHP 版本：7.1
 - MySQL 版本：5.5

**Comment by fateplayer** [comment]
哪位大佬说下这个do是每天运行一次还是一会运行一次

**Comment by n0099** [comment]
> 每天运行一次还是一会运行一次

取决于您的 https://crontab.guru 如何设置的

**Comment by fateplayer** [comment]
> > 每天运行一次还是一会运行一次
> 
> 取决于您的 https://crontab.guru 如何设置的

我想问，是否每天执行一次do就能完成所有签到。

**Comment by n0099** [comment]
> > > 每天运行一次还是一会运行一次
> > 
> > 
> > 取决于您的 [crontab.guru](https://crontab.guru) 如何设置的
> 
> 我想问，是否每天执行一次do就能完成所有签到。

您需要把`/index.php?mod=admin:set:sign`中的
```
单表单次签到执行数量
0为一次性全部签到。此功能非常重要，设置为0会导致每次都扫描贴吧表，效率极低，请按需修改
```
设置项的值改成`0`从而使得每次运行`do.php`时都会同步阻塞（
  如果同时有多个`do.php`在跑就是并行，但如果设置项`贴吧数据表搜寻方法`的值是`永不随机，按顺序抽取`那就会
  > 该模式是数据库性能最高的模式，不会有贴吧漏签，采取"先来后到"的签到原则。但是如果启用了多线程功能，这会导致一个贴吧被重复签到多次，导致整体签到效率降低
  https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/17518f5c727c5790bca5b23f4ca5fd7e7517b742/templates/admin-set.php#L26
）
签到完所有贴吧，然后将`cli/php.ini`中的[`max_execution_time`](https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time)改成`0`，才能实现`每天执行一次do就能完成所有签到`
然而即便如此您还是得祈祷在唯一一次对`do.php`的执行过程中php进程没有提前退出导致半途而废（并且无后续重试）

**Comment by fateplayer** [comment]
> > > > 每天运行一次还是一会运行一次
> > > 
> > > 
> > > 取决于您的 [crontab.guru](https://crontab.guru) 如何设置的
> > 
> > 
> > 我想问，是否每天执行一次do就能完成所有签到。
> 
> 您需要把`/index.php?mod=admin:set:sign`中的
> 
> ```
> 单表单次签到执行数量
> 0为一次性全部签到。此功能非常重要，设置为0会导致每次都扫描贴吧表，效率极低，请按需修改
> ```
> 
> 设置项的值改成`0`从而使得每次运行`do.php`时都会同步阻塞
> 
> * 如果同时有多个`do.php`在跑就是并行，但如果设置项`贴吧数据表搜寻方法`的值是`永不随机，按顺序抽取`那就会
>   > 该模式是数据库性能最高的模式，不会有贴吧漏签，采取"先来后到"的签到原则。但是如果启用了多线程功能，这会导致一个贴吧被重复签到多次，导致整体签到效率降低
>   > https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/17518f5c727c5790bca5b23f4ca5fd7e7517b742/templates/admin-set.php#L26
> 
> 签到完所有贴吧，然后将`cli/php.ini`中的[`max_execution_time`](https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time)改成`0`
> 
> * 也可以不改，因为 https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/17518f5c727c5790bca5b23f4ca5fd7e7517b742/do.php#L7
> 
> 才能实现`每天执行一次do就能完成所有签到` 然而即便如此您还是得祈祷在唯一一次对`do.php`的执行过程中php进程没有提前退出导致半途而废（并且无后续重试）

谢谢解答。

**Comment by n0099** [comment]
https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/17518f5c727c5790bca5b23f4ca5fd7e7517b742/templates/admin-set.php#L27-L28
kenvix神对此tc历史遗留设计进行了复盘： https://www.v2ex.com/t/921128#r_12774486
![image](https://user-images.githubusercontent.com/13030387/222951848-7125b318-53dc-4a7f-a841-940c21ebe07a.png)
