### ISSUE TITLE
docker-compose部署报错 Error: unknown shorthand flag: 'c' in -config

### ISSUE THREAD

**Issue by HCLonely** [MoeNetwork/Tieba-Cloud-Sign#235]
- [x] 我已升级贴吧云签到到最新版本，并且运行了升级脚本
- [x] 我已搜索过 Issue 区，没有找到相关问题

# 问题描述

docker-compose部署后访问网站返回502，查看日志发现报错 `Error: unknown shorthand flag: 'c' in -config`
![image](https://user-images.githubusercontent.com/26346802/221809867-ca43e7b9-36c7-42f6-902e-41c79366f040.png)

# 复现步骤

`docker-compose up -d`

# 环境

 - 云签到版本：Latest
 - 服务器系统和版本：Ubuntu 20.04 LTS
 - 云签到是否在 Docker 中运行：是
 - PHP 版本：
 - MySQL 版本：

**Comment by n0099** [comment]
#232

**Comment by BANKA2017** [comment]
看了一下应该是执行 s6-overlay 启动脚本出现的问题，怀疑是 sed 不再支持这种 flag，但我并不熟悉 sed 的使用

https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/dd29af3ac3d32f1b8983469f54422661200b84c5/docker/s6-overlay/etc/cont-init.d/20-fix-config#L12-L16

**Comment by n0099** [comment]
什么flag？您在macos上用着BSD sed而非GNU/Linux的GNU sed吗？如同 https://github.com/n0099/tbclient.protobuf/issues/2#issuecomment-1416835461
先看看单独执行`cat $file_config -n | grep "DB_USER" | awk '{print $1}'`的结果是什么
以及变量`$file_config`里是不是有可能出现空格或glob等unexpected expansion，如果可能应该套`""`避免word splitting和unexpected expansion
建议直接无脑`set -x`

**Comment by BANKA2017** [comment]
>先看看单独执行cat $file_config -n | grep "DB_USER" | awk '{print $1}'的结果是什么

得到的是对应内容所在的行数，`c` 的作用是将 `c` 后面的内容替换掉前面的行对应的内容

**Comment by n0099** [comment]
为什么不是`grep -n`而是`cat -n`，效果一样但with line num应该在grep一层进行以避免经典[半谓词问题](https://en.wikipedia.org/wiki/Semipredicate_problem)，即假如grep的是数字（但这里是字面量的字符串`"DB_USER"`，建议换成`''`避免expansion）那就会匹配到`cat -n`所附带的line num造成歧义

**Comment by BANKA2017** [comment]
>看了一下应该是执行 s6-overlay 启动脚本出现的问题

我重新看了一下，问题并不在这个脚本，目前不知道问题所在

**Comment by gitcps** [comment]
宝塔环境安装，出现同样的问题
