### ISSUE TITLE
安装完后显示Connection refused

### ISSUE THREAD

**Issue by 623524718** [MoeNetwork/Tieba-Cloud-Sign#248]
# 问题描述
https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/master/docker/docker-compose.yml
使用该docker-compose.yml，仅修改映射端口，安装完后报错
http://192.168.1.100:18080/setup/install.php?step=4
**百度贴吧云签到 - 提示信息 Connection refused**

**Comment by ChellyL** [comment]
你是不是    
> - DB_HOST=db:3306

这个改了，按模板改回来即刻

**Comment by 623524718** [comment]
> 你是不是
> 
> > * DB_HOST=db:3306
> 
> 这个改了，按模板改回来即刻

好的，谢谢
