### ISSUE TITLE
大概只能签到成功200个左右就会失败

### ISSUE THREAD

**Issue by zhufeng** [MoeNetwork/Tieba-Cloud-Sign#262]
- [x] 我已升级贴吧云签到到最新版本，并且运行了升级脚本
- [x] 我已搜索过 Issue 区，没有找到相关问题

# 问题描述

1.添加了3个百度账号，一共407个吧。
>当前已列出 407 个贴吧。已签到 210 个贴吧，还有 197 个贴吧等待签到。

每天几乎都是签到成功大概200个左右的吧，查看签到日志，里面显示未签到的是状态是待签。
定时任务配置为：
```*/20 1-7 * * * /usr/bin/php /home/***/www/tieba/do.php >/dev/null 2>&1```

这个debian12上的版本是完全新搭建的，同样的服务器之前用的是centos7+php74，版本为4.97，从未出现过无法完全签到的问题。

有无办法排查一下是什么原因导致的无法全部签到呢？

# 复现步骤

如上描述。

# 环境

 - 云签到版本：v5.0.1
 - 服务器系统和版本：debian 12 最新补丁
 - 云签到是否在 Docker 中运行：否
PHP 版本：8.2.18 非线程安全
MySQL 版本：10.11.6-MariaDB-0+deb12u1
服务器软件：nginx/1.22.1
服务器系统：Linux 6.1.0-20-amd64 # 1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11) x86_64

**Comment by n0099** [comment]
手动
```bash
php do.php
```
看看

**Comment by BANKA2017** [comment]
我看这 crontab 一天能运行 21 次，默认设置一次签到 10 个贴吧，所以一天共签到 210 个贴吧。去设置里把一次签到贴吧数量改大点吧。

**Comment by zhufeng** [comment]
> 我看这 crontab 一天能运行 21 次，默认设置一次签到 10 个贴吧，所以一天共签到 210 个贴吧。去设置里把一次签到贴吧数量改大点吧。

尝试了一下更改配置，应该是这个原因了，感谢。
