### ISSUE TITLE
手动登录时异常

### ISSUE THREAD

**Issue by DSLZL** [MoeNetwork/Tieba-Cloud-Sign#272]
- [ ] 我已升级贴吧云签到到最新版本，并且运行了升级脚本
- [ ] 我已搜索过 Issue 区，没有找到相关问题

# 问题描述

<img width="586" alt="屏幕截图 2024-11-28 124218" src="https://github.com/user-attachments/assets/6a1eb995-52a4-4afa-bd95-b861f9ee55f5">

# 复现步骤

就手动登录账号

# 环境

 - 云签到版本：5.01
 - 服务器系统和版本：Linux 638cdce001d9 5.15.0-92-generic 102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64
 - 云签到是否在 Docker 中运行：是
 - PHP 版本：7.4.22
 - MySQL 版本：8.4.3

**Comment by DSLZL** [comment]
这勾怎么就打不上去

**Comment by BANKA2017** [comment]
从旧版更新上来的？看截图是缺少列 `portrait` ，请登录后前往 `http://example.com/setup/update.php`（这里的 `example.com` 换成你自己的ip或者域名），从 4.96 升级到 4.97 [ update4.96to4.97.php ] 开始依次安装 `update4.96to4.97.php`，`update4.97to4.98.php`，`update5.00to5.01.php` 这三个

**Comment by DSLZL** [comment]
![Screenshot_20241128_150954.jpg](https://github.com/user-attachments/assets/243a6fce-e506-465d-bd4f-3774691c7e96)
就这两个怎么办？
> 从旧版更新上来的？看截图是缺少列 `portrait` ，请登录后前往 `http://example.com/setup/update.php`（这里的 `example.com` 换成你自己的ip或者域名），从 4.96 升级到 4.97 [ update4.96to4.97.php ] 开始依次安装 `update4.96to4.97.php`，`update4.97to4.98.php`，`update5.00to5.01.php` 这三个

**Comment by BANKA2017** [comment]
> 就这两个怎么办？

那就前往 <https://github.com/MoeNetwork/Tieba-Cloud-Sign/tree/master/setup> 下载对应的那三个文件放到这个目录，然后依次运行

**Comment by DSLZL** [comment]
> > 就这两个怎么办？
> 
> 那就前往 <https://github.com/MoeNetwork/Tieba-Cloud-Sign/tree/master/setup> 下载对应的那三个文件放到这个目录，然后依次运行

![Screenshot_20241128_154052.jpg](https://github.com/user-attachments/assets/83caba7b-0cf5-449d-b6e4-71c66861dfa4)

它现在就变成这样了

**Comment by DSLZL** [comment]
> > > 就这两个怎么办？
> > 
> > 那就前往 <https://github.com/MoeNetwork/Tieba-Cloud-Sign/tree/master/setup> 下载对应的那三个文件放到这个目录，然后依次运行
> 
> ![Screenshot_20241128_154052.jpg](https://github.com/user-attachments/assets/83caba7b-0cf5-449d-b6e4-71c66861dfa4)
> 
> 它现在就变成这样了
还没开始升级就让我卸载它

**Comment by BANKA2017** [comment]
https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/09ca411da65a97808898e639466f85808c491153/setup/update4.96to4.97.php#L11

https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/09ca411da65a97808898e639466f85808c491153/setup/update4.97to4.98.php#L11

https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/09ca411da65a97808898e639466f85808c491153/setup/update5.00to5.01.php#L11

三个文件都删掉这行，再执行
