### ISSUE TITLE
12月26更新后报错 Uncaught Error: Undefined constant "DB_SSL"

### ISSUE THREAD

**Issue by wenyinos** [MoeNetwork/Tieba-Cloud-Sign#280]
- [y] 我已升级贴吧云签到到最新版本，并且运行了升级脚本
- [y] 我已搜索过 Issue 区，没有找到相关问题

# 问题描述

更新后打开主页显示：
`Fatal error: Uncaught Error: Undefined constant "DB_SSL" in ***/lib/mysql_autoload.php:25 Stack trace: #0 ***/init.php(49): require() #1 ***index.php(10): require('...') #2 {main} thrown in ***/lib/mysql_autoload.php on line 25`
在/lib/mysql_autoload.php中去掉25行"DB_SSL"后正常。
# 复现步骤

在线更新后。

# 环境

 - 云签到版本：V5.02
 - 服务器系统和版本：Linux VM-8-2-ubuntu 5.15.0-116-generic #126~20.04.1
 - 云签到是否在 Docker 中运行：否
 - PHP 版本：8.2.19
 - MySQL 版本：5.7.44-log

**Comment by BANKA2017** [comment]
在 `config.php` 后面手动加一行

https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/fcad3292190b8758d404adef6a3fd2b7b4d3f645/config.php#L15

**Comment by n0099** [comment]
#273
