### ISSUE TITLE
do.php 每次只能签到19个贴吧现在么？

### ISSUE THREAD

**Issue by fashioncj** [MoeNetwork/Tieba-Cloud-Sign#3]
do.php 每次只能签到19个贴吧现在么？

**Comment by fashioncj** [comment]
设置-签到设置

单表单次签到执行数量
0为一次性全部签到。此功能非常重要，设置为0会导致每次都扫描贴吧表，效率极低，请按需修改
---
果然一年多了要仔细看功能了。

**Comment by Anapopo** [comment]
not，more times


来自 魅族 MX

-------- 原始邮件 --------
发件人：Jia Chen <notifications@github.com>
时间：周三 12月2日 19:56
收件人：MoeNetwork/Tieba-Cloud-Sign <Tieba-Cloud-Sign@noreply.github.com>
主题：[Tieba-Cloud-Sign] do.php 每次只能签到19个贴吧现在么？ (#3)
