### ISSUE TITLE
更新到最新版本以后  再次点击更新有这个错误

### ISSUE THREAD

**Issue by pxw2002** [MoeNetwork/Tieba-Cloud-Sign#31]
atal error: Call to undefined function curl_reset() in \lib\class.wcurl.php on line 282
是wcurl版本太低么
PHP 版本：5.3.29	非线程安全
Apache

**Comment by kenvix** [comment]
不，是wcurl版本太高了，@FYY @mokeyjay 帮忙修下呗

**Comment by mokeyjay** [comment]
修好了，然而我没有推送权限…… @kenvix

**Comment by mokeyjay** [comment]
已修复。请下载最新版，并解压其中的`lib\class.wcurl.php`文件替换一下即可

**Comment by pxw2002** [comment]
修复了 谢谢
