### ISSUE TITLE
服务器PHP不支持MySql数据库

### ISSUE THREAD

**Issue by stevenzhu25** [MoeNetwork/Tieba-Cloud-Sign#41]
服务器是Centos 7配置Nginx 1.13.6和PHP7.1. PHP7.1已经装了php-mysqli, php-mcrypt等等，但是仍旧显示“服务器PHP不支持MySql数据库”。 求问是当前版本不支持PHP 71么？

网站：
tb.d3x.pw

**Comment by stevenzhu25** [comment]
![image](https://user-images.githubusercontent.com/14189448/32258457-f06a1d2c-be90-11e7-9fa2-674a87ee6c87.png)
![image](https://user-images.githubusercontent.com/14189448/32258469-0395fa74-be91-11e7-9aa1-2601bd58b6f2.png)

**Comment by mokeyjay** [comment]
你看下 `lib/mysql_autoload.php` 内 `SQLMODE`常量的值（一般在第11行）是什么？如果是`mysql`，请改为`mysqli`

**Comment by stevenzhu25** [comment]
您好，

是mysqli的

@mokeyjay 
谢谢

**Comment by mokeyjay** [comment]
这就有点奇怪了，因为mysqli报错应该是“服务器不支持MySqli类”，而不是“服务器PHP不支持MySql数据库”
请你新建一个`test.php`，内容如下：
```php
<?php
var_dump(class_exists("mysqli"));
```
把这个php文件丢到服务器上访问一下

- 如果显示true，可能是代码文件出现问题，建议重新在github拉取代码
- 如果显示false，可能是你的mysqli扩展没装好，程序无法识别到

**Comment by stevenzhu25** [comment]
您好，

显示的是True.
请问有没有可能是和我的服务器为纯英环境有关系呢， 因为我刚刚从另外一台服务器挪过来（虽然那台服务器也是英文）

**Comment by stevenzhu25** [comment]
请问一下，商业版是在哪里选择呢。。

**Comment by mokeyjay** [comment]
应该跟英文环境无关，线上Linux服务器多半都是英文，包括我自己的 :)
建议备份数据库，然后删光代码文件重新拉取（当然，如果有插件的话，也备份一下）

商业版请联系 @kenvix

**Comment by stevenzhu25** [comment]
您好，

我刚刚重新装了程序，这次要求我放置install.lock. 我放置了以后还是一直显示要求install.lock。
