### ISSUE TITLE
不支持PHP7.2？

### ISSUE THREAD

**Issue by ClarkeCheng** [MoeNetwork/Tieba-Cloud-Sign#43]
版本4.9，PHP7.1正常，PHP7.2就无法访问。

**Comment by mokeyjay** [comment]
“无法访问”的具体细节呢？

**Comment by ClarkeCheng** [comment]
@mokeyjay ，用Chrome访问的话就显示这个

This site can’t be reached

The webpage at [当前的地址] might be temporarily down or it may have moved permanently to a new web address.
ERR_CONTENT_DECODING_FAILED

**Comment by MoeGakuen** [comment]
PHP 7.2.0 完美运行
![11](https://user-images.githubusercontent.com/16118914/33699621-3ae74282-db4f-11e7-88ad-2e9767645c6d.png)

**Comment by ClarkeCheng** [comment]
根据@MoeGakuen 的情况，我自己排查了一下，发现是插件GZip 压缩页面(wmzz_gz)造成的，而且在PHP7.2下index.php顶部和服务器信息里会报错。(无关路径已省略)
Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in lib/reg.php on line 94
PHP 版本：7.2.0	非线程安全
MySQL 版本：5.5.57-log

另外，公告栏插件(wmzz_anno)激活时也会报错。
贴吧云签到 - 提示信息

百度贴吧云签到 V4.9 (PHP 7.2.0) 在工作时发生致命的异常 @ 2017-12-07 13:12:35
消息：#0 - Too few arguments to function option::add(), 1 passed in plugins/wmzz_anno/wmzz_anno_callback.php on line 11 and exactly 2 expected

文件 | 行 | 代码
-- | -- | --
lib/class.option.php | 57 | [抛出异常]
plugins/wmzz_anno/wmzz_anno_callback.php | 11 | add
lib/plugins.php | 33 | callback_init
setting.php | 27 | activePlugin

**Comment by mokeyjay** [comment]
喵喵喵？不应该啊，我看`lib/reg.php`明明是有
```php
if (function_exists('spl_autoload_register')) {
	spl_autoload_register('class_autoload');
} else {
	function __autoload($c){
		class_autoload($c);
	}
}
```
这样的判断的，按理来说不会执行到`__autoload`才对的

你创建一个任意名.php，内容为
```php
<?php
var_dump(function_exists('spl_autoload_register'));
```
访问一下看看是返回`true`还是`false`，要是false就奇怪了

**Comment by ClarkeCheng** [comment]
@mokeyjay  我访问了，返回`true`，而且我的`lib/reg.php`的第91行至97行也有这段代码。
```
if (function_exists('spl_autoload_register')) {
	spl_autoload_register('class_autoload');
} else {
	function __autoload($c){
		class_autoload($c);
	}
}
```
为了排除我云签到的文件可能被篡改过的可能，我又下载了最新的源码，全新安装了一个，结果还是报了错。
```
Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in lib/reg.php on line 94
```
P.S：我用的是宝塔linux面板，PHP7.2都是从这里装的。

**Comment by mokeyjay** [comment]
这……大佬 @kenvix 来看看？

**Comment by hank9999** [comment]
吧94行的_autoload改成_sql_autoload就可以了~

**Comment by hank9999** [comment]
亲测7.2.2版本正常，不用改别的

**Comment by ClarkeCheng** [comment]
感谢 @hank9999 ，现在不报错了，而且GZip 压缩页面插件也可以用了。
