### ISSUE TITLE
do.php 未知乱码

### ISSUE THREAD

**Issue by stevenzhu25** [MoeNetwork/Tieba-Cloud-Sign#46]
求问大佬当执行do.php时，显示一堆未知乱码什么鬼...

![image](https://user-images.githubusercontent.com/14189448/36339221-a6bfc14c-138e-11e8-8715-0afd3e19abef.png)

`��X�o�D����p�Bڤ؎��i�$�I��`��4!T]�K|���%i��m�6m�&�^��V>�Quo�L����/p�$��^�T�v����w�=o�����?��N�t���3�e �2�Q��j��iYq,]o��Z;�����bQ_4 �_/+k���s#��Q��FE_6q��,�!��:R�=��V�.`Oۅ!E��d5uQ�86PYia�H� m�0����u2��a�Ԇ*ZVI�1�)%v���+3�� 7$gqS̼��p���a��4S�<��sBQY��9e0^|ထ'T8��j�H�ˁD*#��=f�9�_z��[6O"(�]�@���k�E�{�G��p��1�|Z<�#M�S����&�TYcϳ0�:H3��M2�A|B�kO�GM�/ ��_�x\; }.(�g��Q�ߓL�A6	!Äk�'���Q%�N�b����4�N��ϘF:�Vmr���3zA���%��Xް�'%3��2's0 <�}��KV=b�C�Gs|sAJ/J�G���y��\�`7C*�,	v���1Q�����g�� ��зѡ�� ��b��(P;���m�E����� �6F @:�-8�0�ތ}^�	�DyL�)����j���}�xHz� � B%����2�ٷ>)�U�?\�>{Z�yStw7�����v~�4��#�9��S�[0�4:�R��E)�����k|��y��i�pv'b0�q���{��ۃ�>�Y�pg�n`j�C q{y�� 6mv|����ۧ�ǜey�����@'��������_��PcY��kdR�#,�� ���'�>>���7a؜�!c y#��ԩ�W�"c%p!<�@fy������C�1��]�C�GL_A~��0�Bu�#MG��1�MD�񢍕����һq}����{����cI��D�N���m$�����\H	;�H�'T�$���}u�w������7{�8�	�Q'��[�����`

服务器Centos 7,PHP 7.1,Nginx 1.13环境

跪谢

**Comment by mokeyjay** [comment]
改一下浏览器页面编码试试

**Comment by stevenzhu25** [comment]
@mokeyjay 
您好，

浏览器编码就是UTF-8...
没有任何问题

**Comment by mokeyjay** [comment]
@stevenzhu25 换成GB2312或者GBK呢？

**Comment by kenvix** [comment]
请确保你从未使用过记事本编辑本程序的任何文件。
请确认是否开启了GZIP插件

**Comment by stevenzhu25** [comment]
您好... 

可能是前几天我服务器抽风吧... (昨天突然就正常了）


的确没有拿记事本编辑过任何文件..

也许就是服务器抽风

谢谢
