### ISSUE TITLE
首页https失效

### ISSUE THREAD

**Issue by Google-Android** [MoeNetwork/Tieba-Cloud-Sign#49]
![20180404184732](https://user-images.githubusercontent.com/11240970/38303957-3d3a2d9a-383a-11e8-8fcb-e5f23d23619a.png)
![20180404185424](https://user-images.githubusercontent.com/11240970/38303958-3d6ff97a-383a-11e8-8335-07d1f2cad1a9.png)

查看源代码发现，是因为引用了大量的http链接，劳驾作者修改一下。

**Comment by mokeyjay** [comment]
不，并没有“完全失效”那么危险，只是因为引用了http静态资源而已
印象中只有头像用了http，其他都是自动判断协议的引用
也就是说安全性没有问题的，唯一的缺点是没有小绿锁

我有空改下

**Comment by Google-Android** [comment]
@mokeyjay 非常感谢

**Comment by kenvix** [comment]
不是程序的问题。请在站点设置中更改“站点地址”为https://

**Comment by Google-Android** [comment]
@kenvix 
谢谢回复，不过我的默认设置就是https，我查看网页源码，里面引用了20个http的资源，这个应该是问题所在
![image](https://user-images.githubusercontent.com/11240970/38344880-8171b3fa-38be-11e8-83c8-56dea3de5d73.png)

**Comment by mokeyjay** [comment]
@Google-Android 已解决，请更新

**Comment by Google-Android** [comment]
@mokeyjay 辛苦了，谢谢付出
