### ISSUE TITLE
do.php密码错误

### ISSUE THREAD

**Issue by qbyyy** [MoeNetwork/Tieba-Cloud-Sign#66]
不管是通过前台还是命令，都提示密码错误，这里的密码是管理员的密码吗？
![image](https://user-images.githubusercontent.com/32118604/48746722-951bf400-ecab-11e8-8aed-bcd9c4febcc7.png)
![image](https://user-images.githubusercontent.com/32118604/48746736-a9f88780-ecab-11e8-8d0c-5b8afcdc97db.png)

**Comment by mokeyjay** [comment]
是管理员设置里的 **计划任务密码**
