### ISSUE TITLE
没有域名只监控ip地址云签会自运行吗

### ISSUE THREAD

**Issue by bolis-WeiLian** [MoeNetwork/Tieba-Cloud-Sign#68]
就是说用 http云监控 能监控 xxx.xxx.xxx.xxx/do.php 来让云签自动运行吗

**Comment by mokeyjay** [comment]
如果你的 xxx.xxx.xxx.xxx/do.php 能够访问的话就行

**Comment by Xuchenhao** [comment]
可以，但是你的do.php必须要可以从浏览器访问到。
