### ISSUE TITLE
贴吧签到异常提示

### ISSUE THREAD

**Issue by HCLonely** [MoeNetwork/Tieba-Cloud-Sign#80]
异常#1023：您尚在黑名单中，不能操作。
异常#11000：您还未加入此吧或等级不够
异常#1010：抱歉，根据相关法律法规和政策，本吧暂不开放。

**Comment by mokeyjay** [comment]
请问你想表达什么？

**Comment by 96dl** [comment]
请问你想表达啥？提供的三个状态码似乎没一个是对的，

**Comment by HCLonely** [comment]
> 请问你想表达啥？提供的三个状态码似乎没一个是对的，

签到结果里这三个异常都是显示签到太频繁了，我每个点进去手动签就是这三个提示

**Comment by 96dl** [comment]
麻烦提供下截图，这边看了这三个状态码，除了11000是未知错误之外，别的都是没有出现过的

**Comment by HCLonely** [comment]
![批注 2019-08-21 141637](https://user-images.githubusercontent.com/26346802/63407468-2f69bd80-c41f-11e9-869f-ed465d094146.png)
![批注 2019-08-21 141732](https://user-images.githubusercontent.com/26346802/63407469-30025400-c41f-11e9-898f-be5323326cdf.png)
![批注 2019-08-21 142223](https://user-images.githubusercontent.com/26346802/63407484-3395db00-c41f-11e9-8764-9a3000ea8e31.png)
![批注 2019-08-21 141828](https://user-images.githubusercontent.com/26346802/63407470-30025400-c41f-11e9-916a-a939ab9129ef.png)
![批注 2019-08-21 141856](https://user-images.githubusercontent.com/26346802/63407474-309aea80-c41f-11e9-86b1-5b39010fd848.png)
![批注 2019-08-21 141939](https://user-images.githubusercontent.com/26346802/63407481-3264ae00-c41f-11e9-8ca8-38cd81fb726a.png)
![批注 2019-08-21 142126](https://user-images.githubusercontent.com/26346802/63407482-32fd4480-c41f-11e9-88f2-0459564c636b.png)
![批注 2019-08-21 142151](https://user-images.githubusercontent.com/26346802/63407483-32fd4480-c41f-11e9-9ecf-afd025533d4e.png)

**Comment by 96dl** [comment]
黑名单的看起来没啥问题，签到太频繁的是度娘接口返回的，建议使用客户端签到，而非网页签到，度娘改动比较多，，，可能网页签到会有各种各样的问题

**Comment by HCLonely** [comment]
好的
