### ISSUE TITLE
V4.9 刷新贴吧列表不可用

### ISSUE THREAD

**Issue by ippdesu** [MoeNetwork/Tieba-Cloud-Sign#84]
无法刷新，可以手动添加，有无大佬解惑，是百度问题还是接口改了呢

**Comment by Google-Android** [comment]
遇到同样的问题了，希望作者可以修复一下，感谢

**Comment by n0099** [comment]
pch的自动刷新贴吧列表插件的接口还能用：https://github.com/chajianku/pch18_relist

**Comment by kenvix** [comment]
#87 似乎已修复此问题

**Comment by n0099** [comment]
> #87 似乎已修复此问题

没修，pch的接口就是调用tc的方法，估计是百度的问题

**Comment by sxx1314** [comment]
没修复
