### ISSUE TITLE
无法签到

### ISSUE THREAD

**Issue by Rakau** [MoeNetwork/Tieba-Cloud-Sign#89]
最近几天出现的问题，计划任务都是正常运行，前端也提示状态正常，但是实际进入贴吧里面都是未签状态 

![TIM截图20210204140223](https://user-images.githubusercontent.com/33389179/106851679-a49f8000-66f1-11eb-8d8d-7dc78db0aa03.png)

**Comment by BANKA2017** [comment]
将源码所有的 fucking phone 或者 fuck phone 的ua删掉，有好几个，慢慢找
比如 https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/4a36813643eb0658bcc690c4c630b6123029d917/lib/class.misc.php#L149

**Comment by Rakau** [comment]
感谢回复

BANKA2017 <notifications@github.com> 于 2021年2月4日周四 16:04写道：

**Comment by kenvix** [comment]
( ﾟ∀。) 这...

**Comment by shanghaobo** [comment]
也遇到这个问题了，怎么解决呀，删掉fuck phone的UA也不行

**Comment by shanghaobo** [comment]
解决了，把Fucking phone也删掉可以了

**Comment by Hobr** [comment]
~~没人开个pr解决一下吗~~

**Comment by Rakau** [comment]
> ~~没人开个pr解决一下吗~~

我把我的提交会被合并吗
