### ISSUE TITLE
这是侵权吗？

### ISSUE THREAD

**Issue by slanterns** [MoeNetwork/Tieba-Cloud-Sign#9]
s.1234.pink
![_2016-04-27t16-07-44 844z](https://cloud.githubusercontent.com/assets/10987206/14859127/57946cce-0cd5-11e6-8ed2-d1dc9fee9f97.png)

**Comment by kenvix** [comment]
大脑是好的，但不是每个人都有

**Comment by Z4HD** [comment]
耻辱柱上又多了一位勇士
