### ISSUE TITLE
使用腾讯云香港轻量服务器搭建云签后无法使用

### ISSUE THREAD

**Issue by BANKA2017** [MoeNetwork/Tieba-Cloud-Sign#95]
- 问题描述：腾讯云香港轻量请求贴吧接口会随机出现卡死阻塞后续脚本的执行，这种问题出现在任何 `tieba.baidu.com` 下面的链接
- 系统环境：模板中的 Ubuntu 20.04 LTS，清除了自带的监控
- 复现方式：使用 **腾讯云香港轻量服务器** 在终端反复运行 `curl "https://tieba.baidu.com"` 直到出现卡死，立即执行 ctrl+c 终止后再次执行仍会卡死。但在等几秒又恢复正常
- 临时解决想法：在 wcurl 加入超时重连机制

猜测是腾讯云的限制，我使用国内外多台服务器都未能复现，不知道有没有什么方法能解决这个问题

**Comment by n0099** [comment]
建议re-open issue
