### ISSUE TITLE
您的 BDUSS Cookie 信息有误，请核验后重新绑定

### ISSUE THREAD

**Issue by gynotes** [MoeNetwork/Tieba-Cloud-Sign#96]
您的 BDUSS Cookie 信息有误，请核验后重新绑定

大佬这个问题怎么解决？bduss是对的，但是就是无法绑定上

**Comment by luikhh** [comment]
我的也是这样，试了好几个号，自动绑定和手动获取BDUSS都不行

**Comment by ChloeKurumi** [comment]
同问，用别人家的云签，结果老报错绑不上，换了几家都不行，于是又自己搭，还是不行......bduss是对的，毕竟找了家收费的云签都绑上了......

**Comment by minnyres** [comment]
我的也是这样，无法绑定

**Comment by minnyres** [comment]
有人提供了解决方法，需要自己修改代码

https://gitee.com/kenvix/Tieba-Cloud-Sign/issues/I3PJKJ

**Comment by luoli233** [comment]
> 有人提供了解决方法，需要自己修改代码
> 
> https://gitee.com/kenvix/Tieba-Cloud-Sign/issues/I3PJKJ

按照这个教程改的还是无法登陆

**Comment by ChloeKurumi** [comment]
> > 有人提供了解决方法，需要自己修改代码
> > https://gitee.com/kenvix/Tieba-Cloud-Sign/issues/I3PJKJ
> 
> 按照这个教程改的还是无法登陆

亲测有效，已经绑定成功了
