### ISSUE TITLE
提交更改和退出登录时提示CSRF防御错误

### ISSUE THREAD

**Issue by INDEXxiaoxia** [MoeNetwork/Tieba-Cloud-Sign#99]
config中的CSRF已设置为false
菜单里的所有功能提交更改时，和退出登录时提示CSRF防御错误
![QQ截图20210623092330](https://user-images.githubusercontent.com/43598840/123020419-cd0bea80-d404-11eb-871f-081791a03832.png)

**Comment by BANKA2017** [comment]
临时解决措施是在 config.php 里面把ANTI_CSRF设置为false
彻底解决问题需要检查http服务器的配置，比如nginx默认配置的 `server_name` 是下划线 `_`，直接ip访问是可行的，但会过不了csrf的检查
我建议云签程序开放管理员设定网站域名便于处理csrf检查

**Comment by kenvix** [comment]
已修复 #109
